### ISSUE TITLE
Deploying

### ISSUE THREAD

**Issue by geraldus** [ghcjs/ghcjs#266]
I've faced this issue: my GHCJS application starts from time to time, it looks like RTS system silently fails to start. There are about 170k line of code in `all.js`.

So I decided to minify my application code. First, there is `-DGHCJS_BROWSER` mentioned in deployment wiki, however, I've been used `-DBROWSER_ONLY` all the time, which one of them is right choice (or are they synonyms)?
Then, I tried to use Closure Compiler. I've installed it as suggested via NPM, but this installation fails every time with Java's `OutOuMemoryError` (I tried SIMPLE and ADVANCED optimisations), online CC service could compile my code too when I select advanced optimisations, failing with -1 error without any description; simple optimisation works, but compression profit is only 15% un this case.

Could anybody help me?

**Comment by Mikolaj** [comment]
I've had the same problem with the closure compiler linked from the wiki page https://github.com/ghcjs/ghcjs/wiki/Deployment. But with the newest closure compile from Google, it handles my 14M JS code well with ADVANSED_OPTIMIZATION (and reduces it to 4M).
