### ISSUE TITLE
Event handling seems to kill running thread

### ISSUE THREAD

**Issue by the-real-blackh** [ghcjs/ghcjs#291]
This program has animated 2D graphics. It seems that the animation thread stops dead when any callback to Haskell is handled. I expect the animation to keep running forever.

To reproduce the problem, go to this URL. You should see red, green, blue colours sweeping across the page. If you click on the window, the animation will stop. putStrLns indicate that the 'forever' loop has stopped running.

http://hip-to-be-square.com/~blackh/helloWorld.jsexe/

Same behaviour in Firefox and Chrome (tested on Ubuntu).

The code can be downloaded with this command:
git clone http://hip-to-be-square.com/~blackh/ghcjs-bug-report/

    {-# LANGUAGE ForeignFunctionInterface, JavaScriptFFI, EmptyDataDecls, OverloadedStrings #-}
    
    import Control.Concurrent
    import Control.Monad
    import Control.Monad.Trans
    import Data.IORef
    import GHCJS.Foreign
    import GHCJS.Types
    import GHCJS.Marshal
    import GHCJS.DOM (currentDocument, currentWindow)
    import GHCJS.DOM.Document
    import GHCJS.DOM.Element
    import GHCJS.DOM.DOMWindow
    import GHCJS.DOM.HTMLCanvasElement
    
    data Context_
    type Context = JSRef Context_
    
    foreign import javascript unsafe "$1.getContext($2)"
        getContext :: HTMLCanvasElement -> JSString -> IO Context
    
    foreign import javascript unsafe "$1.fillStyle = $2;"
        setFillStyle :: Context -> JSString -> IO ()
    
    foreign import javascript unsafe "$1.fillRect($2,$3,$4,$5);"
        fillRect :: Context -> Int -> Int -> Int -> Int -> IO ()
    
    foreign import javascript unsafe "window.innerWidth"
        innerWidth :: IO Int
    
    foreign import javascript unsafe "window.innerHeight"
        innerHeight :: IO Int
    
    resize :: HTMLCanvasElement -> IORef (Int, Int) -> IO ()
    resize canvas sizeRef = do
        wd <- innerWidth
        ht <- innerHeight
        htmlCanvasElementSetWidth canvas wd
        htmlCanvasElementSetHeight canvas ht
        putStrLn $ "canvas is "++show wd ++ "x"++ show ht
        writeIORef sizeRef (wd, ht)
    
    draw :: HTMLCanvasElement -> IORef (Int, Int) -> JSString -> Int -> IO ()
    draw canvas sizeRef colour x = do
        ctx <- getContext canvas "2d"
        (wd, ht) <- readIORef sizeRef
        setFillStyle ctx "#FFFFFF"
        fillRect ctx 0 0 wd ht
        setFillStyle ctx colour
        fillRect ctx 5 5 ((x * (wd - 10)) `div` 100) (ht - 10)
    
    main = do
        Just doc <- currentDocument
        Just win <- currentWindow
        Just canvas0 <- documentGetElementById doc ("myCanvas" :: JSString)
        let canvas = castToHTMLCanvasElement canvas0
        sizeRef <- newIORef (0,0)
        resize canvas sizeRef
        -- What we were trying to do
        --domWindowOnresize win $ liftIO $ resize canvas sizeRef
    
        -- A minimal event handler that demonstrates the same problem
        -- Click on the window and the animation will stop dead
        Just body <- documentGetBody doc
        elementOnclick body $ return ()
    
        forever $ do
            forM_ ["#FF0000", "#00FF00", "#0000FF"] $ \colour -> do
                forM_ [0,10..100] $ \x -> do
                    putStrLn $ show x
                    draw canvas sizeRef colour x
                    threadDelay 100000

**Comment by luite** [comment]
should be fixed, please reopen if you still see the problem

**Comment by the-real-blackh** [comment]
Confirmed fixed.
