### ISSUE TITLE
FFI passes unevaluated thunk to JavaScript

### ISSUE THREAD

**Issue by ryantrinkle** [ghcjs/ghcjs#307]
The following program should produce 3 checkboxes: `[ ]  [X]  [ ]`.  It does this correctly under GHC and under GHCJS with -O1 or -O2.  However, under GHCJS with -O0, it produces `[ ] [X] [X]`.  This appears to be due to an unevaluated thunk being passed into JavaScript via htmlInputElementSetChecked.  Since the thunk is an object, it is "truthy" in JavaScript.

```haskell
import GHCJS.DOM
import GHCJS.DOM.Element
import GHCJS.DOM.Document
import GHCJS.DOM.HTMLInputElement
import GHCJS.DOM.Node
import GHCJS.DOM.Types hiding (Event)

main :: IO ()
main = runWebGUI $ \webView -> do
  Just doc <- fmap (fmap castToHTMLDocument) $ webViewGetDomDocument webView
  Just body <- documentGetBody doc
  let testCheckbox x = do
        Just e <- fmap (fmap castToHTMLInputElement) $ documentCreateElement doc "input"
        elementSetAttribute e "type" "checkbox"
        htmlInputElementSetChecked e x
        _ <- nodeAppendChild body $ Just e
        return ()
  testCheckbox False
  testCheckbox True
  testCheckbox $ id False
```

**Comment by luite** [comment]
ah that looks bad. I'll look into this, might be some wonky desugaring of ffi code in combination with GHCJS' use of unboxed booleans that causes this.

(sorry for the late reply, I've been on a bad connection the past days)

**Comment by ryantrinkle** [comment]
OK, it looks like the issue only occurs when you have two modules compiled with different levels of optimization:

```haskell
module Blah where

foreign import javascript unsafe "console.log($1)" consoleLogBool :: Bool -> IO ()
```

```haskell
import Blah

main :: IO ()
main = do
  consoleLogBool False
  consoleLogBool True
  consoleLogBool $ id False
```

```bash
ghcjs -O2 Blah.hs && ghcjs -O0 Main.hs && node Main.jsexe/all.js
```

Output:
```
[1 of 1] Compiling Blah             ( Blah.hs, Blah.js_o )
[2 of 2] Compiling Main             ( Main.hs, Main.js_o )
Linking Main.jsexe (Blah,Main)
false
true
{ d1: null,
  d2: null,
  f: { [Function: h$$lA] t: 0, i: [], n: '', a: 0, r: 256, s: [ [Object] ], m: 0, size: 0 },
  m: 0 }
```

**Comment by luite** [comment]
hm, this does not happen on GHCJS compiled with GHC 7.10

**Comment by luite** [comment]
can't reproduce it on 7.8.4 either.

**Comment by luite** [comment]
a strictness bug was fixed some time ago with https://github.com/ghcjs/ghcjs/commit/50b906ccad110d7b8a6475ad4b14e1597df0887a

please reopen if it still happens after this.

**Comment by quyse** [comment]
I think I just hit this. Unfortunately it's a lot of code, I tried to extract small code snippet for repro, with no luck. So, here is the [code file](https://github.com/quyse/flaw/blob/a4e3b5bb7c3d65c59f63fd77f447a205faa93826/flaw-webgl/Flaw/Graphics/WebGL.hs), and the chunk in the end of `webglUpdateContext` function:

```Haskell
let normalized n = case n of
	NonNormalized -> False
	Normalized -> True
let stn q = case q of
	ATFloat32 -> (1, webgl_FLOAT, False)
	ATInt32 n -> (1, webgl_INT, normalized n)
	ATInt16 n -> (1, webgl_SHORT, normalized n)
	ATInt8 n -> (1, webgl_BYTE, normalized n)
	ATUint32 n -> (1, webgl_UNSIGNED_INT, normalized n)
	ATUint16 n -> (1, webgl_UNSIGNED_SHORT, normalized n)
	ATUint8 n -> (1, webgl_UNSIGNED_BYTE, normalized n)
	ATVec1 a -> let (_, t, n) = stn a in (1, t, n)
	ATVec2 a -> let (_, t, n) = stn a in (2, t, n)
	ATVec3 a -> let (_, t, n) = stn a in (3, t, n)
	ATVec4 a -> let (_, t, n) = stn a in (4, t, n)
	_ -> error $ show ("wrong WebGL attribute type", at)
let (aSize, aType, aNormalized) = stn at
js_vertexAttribPointer jsContext i aSize aType aNormalized stride offset
```
Here `aNormalized` is a `Bool` variable, and canvas tracer in Firefox shows that it's an Object sent to `vertexAttribPointer`, which is interpreted as `true` and screws up rendering. If I change the last lines to this:
```Haskell
let (aSize, aType, aNormalized) = stn at
nnn <- evaluate aNormalized
js_vertexAttribPointer jsContext i aSize aType nnn stride offset
```
it works as intended, and tracer correctly shows `false`.
I'm on latest improved-base e7b3b0099258d0739e46b1dcefb2d2793dbbc8fd. Optimization level is -O2.
Maybe you can get something from this. I'll try to make a small reproducible case.
