### ISSUE TITLE
Cabal: could not resolve dependencies

### ISSUE THREAD

**Issue by rubenmoor** [ghcjs/ghcjs#308]
Hi everyone!

I managed to install ghcjs according to the instructions. However, when I try to use ghcjs cabal fails to resolve dependencies:

cabal install --ghcjs
> trying: digestive-functors-0.7.1.4/installed-06b... (user goal)
> trying: hutcheson-client-0.1.0.0 (user goal)
> next goal: digestive-functors-blaze (dependency of hutcheson-client-0.1.0.0)
> rejecting: digestive-functors-blaze-0.6.0.4, 0.6.0.3 (conflict: digestive-functors => text==1.2.0.3/installed-486..., digestive-functors-blaze => text>=0.11 && <1.2)
> ...

I am installing inside a sandbox and I tried plain hackage as well as `cabal.config` files from stackage (LTS 1.2 and 1.9). But I don't even know where the packages live that are installed with the --ghcjs flag.

Any idea how to approach this? All help is appreciated.

**Comment by rubenmoor** [comment]
I tried with deleting `~/.ghcjs` and rerunning `ghcjs-boot --init` and `ghcjs-boot --dev`. Does the file `~/.cabal/cabal.config` actually has any influence?

**Comment by geraldus** [comment]
Oh course it does. For example, I use `cabal.config` from Stackage to build my web app, but to generate Javasript by GHCJS I can't because it makes dependencies unresolved. In past I had GHCJS installed in host OS, OS X in my case, but for now I've decided to isolate GHCJS withing virtual  machine and separated normal Haskell code from code which should be converted to `javascript`.

**Comment by rubenmoor** [comment]
I put a suitable `cabal.config` in my home directory, but `ghcjs-boot --dev` seems to ignore it. The `cabal.config` says

    digestive-functors ==0.7.1.1,

However, after having run `ghcjs-boot --dev`:

    $ cabal install --ghcjs digestive-functors

gives

    All the requested packages are already installed:
    digestive-functors-0.7.1.4

And more importantly
    
    cabal install --ghcjs digestive-functors-blaze

still gives the above `could not resolve dependencies`. Even with `max-backjumps=-1` => Dependency Tree exhaustively searched.

**Comment by rubenmoor** [comment]
Could it be that my problem is the following:

    rejecting: ghcjs-base-0.1.0.0/installed-4b1... (conflict: ghcjs-base => text==1.2.0.3/installed-486..., digestive-functors-blaze => text>=0.11 &&<1.2)

I.e. `ghcjs-base` does not work together with `digestive-functors-blaze` in any possible combinations of version, anymore?

**Comment by luite** [comment]
`ghcjs-boot` builds a base set of libraries for the compiler and ignores existing `cabal.config` files. when you install packages yourself, the configuration is taken into account.

I think this problem has been resolved by now, at least the upper bound for `text` in `digestive-functors-blaze` has been bumped. If you run into this in the future, you can use things like `--constraint=blaze-builder installed` and `--allow-newer=text` to work around the problem.
