### ISSUE TITLE
Installation on windows failed

### ISSUE THREAD

**Issue by wrvn** [ghcjs/ghcjs#322]
On my Windows 8.1 and GHC-7.8.4 32-bit running ```ghcjs-boot --dev``` failed with
```
System\Process.hs:93:8:
    Could not find module `System.Posix.Process'
    Perhaps you meant
      System.Win32.Process (from Win32-2.3.1.0)
      System.Posix.Types (from base)
    Use -v to see a list of the files searched for.

System\Process.hs:111:8:
    Could not find module `System.Posix.Signals'
    Perhaps you meant System.Posix.Internals (from base)
    Use -v to see a list of the files searched for.
```
From looking into Process.hs it seems ```mingw32_HOST_OS``` preprocessor variable is not defined resulting in wrong imports.

**Comment by luite** [comment]
I'll look into this. I probably missed some preprocessor directives when updating the package.

**Comment by luite** [comment]
windows build works in `improved-base` branch, see `utils/install.ps1` for a script with all the steps. should be merged into master soon
