### ISSUE TITLE
ghcjs-boot --dev fails inside sandbox with ghcjs-pkg not found

### ISSUE THREAD

**Issue by eallik** [ghcjs/ghcjs#323]
I successfully installed GHCJS inside a sandbox; I then ran:

    PATH=.cabal-sandbox/bin:$PATH ghcjs-boot --dev

which failed with

    ghcjs-boot: user error (shelly did not find .cabal-sandbox/bin/ghcjs-pkg in the PATH)

cabal:version 1.22.2.0
GHC version: 7.8.3 (Haskell Platform via brew cask)
OS X version: 10.9.5

**Comment by luite** [comment]
you should probably use a full (absolute) path for your `PATH` variable, since `ghcjs-boot` will be running the commands from a different location (the ghcjs library directory)

**Comment by luite** [comment]
reopen if it was something else
