### ISSUE TITLE
Drop dependency on haskell-src-exts and haskell-src-meta?

### ISSUE THREAD

**Issue by mgsloan** [ghcjs/ghcjs#324]
While this doesn't cause me any big issues, I initially ran into some issues building ghcjs on GHC-7.10, due to haskell-src-meta.  Turned out I just needed to `cabal update`, but I was curious to see where these dependencies came from, particularly because haskell-src-exts is notorious for its long build times.

Turns out it's just for JMacro:

https://github.com/ghcjs/ghcjs/search?utf8=%E2%9C%93&q=Language.Haskell.Exts.Meta&type=Code

This allows antiquotation of haskell code in jmacro.  However, do we really need full blown haskell antiquotation?  I searched for usages:

https://github.com/ghcjs/ghcjs/search?utf8=%E2%9C%93&q=%5Bje%7C&type=Code

And it looks like there's only one that has an antiquote that isn't a variable or constructor: https://github.com/ghcjs/ghcjs/blob/89472a7406f7e8ffbb0842596b0e8a07ae10b516/src/Gen2/RtsApply.hs#L375

Should I put together a patch that removes these dependencies?

**Comment by ddssff** [comment]
I would +1 this idea.  I seem to remember Luite saying the haskell-src-meta dependency would go away.

**Comment by luite** [comment]
The new codegen that I've been working on gets rid of JMacro entirely and in the process drops these dependencies.

**Comment by mgsloan** [comment]
Cool!  I'll hold off on this, then.
