### ISSUE TITLE
Problem installing ghcjs

### ISSUE THREAD

**Issue by Yiyue15** [ghcjs/ghcjs#326]
I've installed ghcjs by the command `cabal install ./ghcjs ./ghcjs-prim` and everything worked out fine and I got something like

    (lines omitted)....
    Installed ghcjs-0.1.0
    Updating documentation index MyDir/Haskell/share/doc/x86_64-osx-ghc-7.8.3/index.html

But when I tried the command `ghcjs-boot --dev` I got `-bash: ghcjs-boot: command not found`
Does anyone know what's wrong here?

**Comment by luite** [comment]
You should update your PATH variable to add the installation location. If you don't know where that is, use the `-v` flag to get more information about where cabal is installing your files: `cabal install -v ./ghcjs ./ghcjs-prim`

**Comment by luite** [comment]
I assume this has been resolved by now. Reopen if not.
