### ISSUE TITLE
Parse of field version failed

### ISSUE THREAD

**Issue by snoyberg** [ghcjs/ghcjs#331]
When running `ghcjs-boot --dev`, I get the following:

```
/home/vagrant/haskell/ghcjs$ [ghcjs-pkg]: /home/vagrant/.cabal/bin/ghcjs-pkg "recache" "--global" "--no-user-package-db"
ghcjs-boot: error running: /home/vagrant/.cabal/bin/ghcjs-pkg recache --global --no-user-package-db
exit status: 1
stderr: ghcjs-pkg-0.1.0-7.8.4: 2: Parse of field 'version' failed.
```

I'm on Ubuntu 14.04 64-bit, with GHC 7.8.4. Just running `ghcjs-pkg list` gives the same output. Any advice on debugging this?

**Comment by snoyberg** [comment]
Interestingly, it seems that having `Cabal-ide-backend` installed was the crux of the matter. It somehow corrupted the contents of the Cabal .conf file in the package database.

**Comment by luite** [comment]
`ghcjs-pkg` is basically `ghc-pkg` with some minor adjustments to get the names and package db locations right. Is there still a problem with it, or does `Cabal-ide-backend` take all the blame?

**Comment by snoyberg** [comment]
There seem to be two problems:

1. Why `Cabal-ide-backend` would end up getting selected if it's installed
2. Why its presence would cause the version field to be unparseable

If you'd rather ignore this and focus on more important issues, that's fine, and I can close. But there *is* something funny going on.

**Comment by mgsloan** [comment]
I'm also running into this issue if I install ghcjs after `Cabal-ide-backend`.  I figured it out!

`Cabal` is a member of `state1PretendToHave`:  https://github.com/ghcjs/ghcjs/blob/64c3768186d73d8c185b42d4d14dfb943919ee56/lib/etc/boot.yaml#L39

However, when selecting which installed package to fake, it uses a prefix match: https://github.com/ghcjs/ghcjs/blob/64c3768186d73d8c185b42d4d14dfb943919ee56/src-bin/Boot.hs#L885

Not sure what the best resolution of this would be - probably parsing the IDs into `(name, version, hash)`?  For now, for my own use, I will just reverse the list of packages that match the prefix! :)

**Comment by snoyberg** [comment]
Awesome sleuthing @mgsloan :cake:
