### ISSUE TITLE
sandboxed ghcjs support?

### ISSUE THREAD

**Issue by mmaz** [ghcjs/ghcjs#334]
Does cabal support the use of GHCJS when the latter was built inside a sandbox? Are there instructions available on how to do so, if it does? I tried the following but got a "GHCJS not found" message:

```
$ git clone https://github.com/ghcjs/ghcjs-jquery && cd ghcjs-jquery
$ cabal sandbox init
$ cabal install --ghcjs
Resolving dependencies...
Notice: installing into a sandbox located at
/Users/*****/ghcjs-jquery/.cabal-sandbox
Configuring data-default-class-0.0.1...
Configuring ghcjs-dom-0.1.1.3...
Failed to install data-default-class-0.0.1
Build log ( /Users/****/ghcjs-jquery/.cabal-sandbox/logs/data-default-class-0.0.1.log ):
Configuring data-default-class-0.0.1...
setup-Simple-Cabal-1.22.0.0-x86_64-osx-ghcjs-0.1.0: The program 'ghcjs'
version >=0.1 is required but it could not be found.
Failed to install ghcjs-dom-0.1.1.3
```

but ghcjs is in my path:
```
$ which ghcjs
$ /Users/*****/bin/ghcjs/.cabal-sandbox/bin/ghcjs
```

I followed the installation instructions [here](https://github.com/ghcjs/ghcjs#install-ghcjs) but in the parent directory, I first created a sandbox:

```
$ cabal sandbox init
$ git clone https://github.com/ghcjs/ghcjs-prim.git
$ git clone https://github.com/ghcjs/ghcjs.git
$ cabal install ./ghcjs ./ghcjs-prim
```

After adding the `/path/to/.cabal-sandbox/bin/` to my terminal path (OSX) I was able to run `ghcjs-boot --dev` successfully (I have the `~/.ghcjs/x86_64-darwin-0.1.0-7.8.3/ghcjs/ghcjs_boot.completed` file, with `full` as contents).

More broadly, if there's is a way to fully sandbox the ghcjs-boot packages and ghcjs itself, instructions would be greatly appreciated! I'd really like to start using ghcjs but as a heavy sandbox user (stackage nightly is used in all of my projects) I don't want to have any libraries listed in my global or user package lists:
```
$ ghc-pkg list --global
$ ghc-pkg list --user
```
But all the instructions in the [README](https://github.com/ghcjs/ghcjs/blob/master/README.markdown) assume users are willing to install things outside of sandboxes. Thanks!

**Comment by mmaz** [comment]
Relatedly, does ghcjs support the [`-package-db`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/packages.html#package-databases) flag or [`GHC_PACKAGE_PATH`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/packages.html#ghc-package-path) environment variable?

To temporarily work around my above issue, I used docker to sandbox a ghcjs install (thanks for the [Dockerfile](https://github.com/ghcjs/ghcjs/blob/master/Dockerfile)!) but noticed the following issue - the verbose output when running `ghcjs -v` suggests it's still trying to use the packages only in `~/.ghcjs/` and not in my sandbox:

```
$ export GHC_PACKAGE_PATH=$PWD/.cabal-sandbox/x86_64-linux-ghc-7.8.4-packages.conf.d/
$ ghcjs -v -package-db=.cabal-sandbox/x86_64-linux-ghc-7.8.4-packages.conf.d/ -iexamples/ -isrc/ examples/Main.hs
Glasgow Haskell Compiler for JavaScript, Version 7.8.4, stage 2 booted by GHC version 7.6.3
Using binary package database: /root/.ghcjs/x86_64-linux-0.1.0-7.8.4/ghcjs/package.conf.d/package.cache
Using binary package database: /root/.ghcjs/x86_64-linux-0.1.0-7.8.4/package.conf.d/package.cache
```

I've provided a longer output in an issue in [ghcjs-react](https://github.com/fpco/ghcjs-react/issues/1) where I successfully installed the ghcjs-react library in a sandbox, but had the above problem pointing `ghcjs` at my sandbox. Thanks!

**Comment by luite** [comment]
GHCJS can be built in a sandbox, but when running `ghcjs-boot` a Cabal library that supports GHCJS needs to be visible to the `ghc` command that `ghcjs-boot` uses. Since `ghcjs-boot` depends on data files installed when building GHCJS, the sandbox should not be moved.

The locations of the GHCJS package DB are not sandboxed by default. The global package DB location is determined by the `-B` command line option. Usually, the `ghcjs` command is a wrapper script that calls the underlying ghcjs binary with the correct db location. GHCJS uses `GHCJS_PACKAGE_PATH` for custom user package db locations.

**Comment by mmaz** [comment]
Thanks for the help!! The `-B` flag in the `ghcjs` and `ghcjs-pkg` scripts that you mentioned, plus your comments in [this issue](https://github.com/ghcjs/ghcjs/issues/353#issuecomment-107023505) helped me out a lot, and allowed me to configure both cabal sandboxes and 'sandboxy' isolation of ghcjs-boot packages (in order to have different versions of the ghcjs-boot dependencies available on the same system)
