### ISSUE TITLE
Error: spawn EBADFcabal.exe (Windows 32bit?)

### ISSUE THREAD

**Issue by BethAr** [ghcjs/ghcjs#342]
I managed to build GHCJS three times now, on three different machines, all with Windows 7 64bit installed. However, I have a machine with Windows 7 32bit in which I'm completely unable to overcome this bug:
```
[79 of 79] Compiling Main             ( boot\cabal\Cabal\dist\setup\setup.hs, boot\cabal\Cabal\dist\setup\Main.js_o )

(some lines omitted)
Configuring Cabal-1.22.2.0...
Building Cabal-1.22.2.0...
Failed to install Cabal-1.22.2.0
JavaScript exception: Error: spawn EBADFcabal.exe: Error: some packages failed to install:
Cabal-1.22.2.0 failed during the building phase. The exception was:
ExitFailure 1
ghcjs-boot.exe: error running: C:\Users\Beta\AppData\Roaming\cabal\bin\cabal.exe --config-file C:\Users\Beta\AppData\Roaming\ghcjs\i386-mingw32-0.1.0-7.10.1\ghcjs\cabalBootConfig install ./boot/cabal/Cabal --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler C:\Users\Beta\AppData\Roaming\cabal\bin\ghcjs.exe --with-hc-pkg C:\Users\Beta\AppData\Roaming\cabal\bin\ghcjs-pkg.exe --prefix C:\Users\Beta\AppData\Roaming\ghcjs\i386-mingw32-0.1.0-7.10.1\ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-library-profiling --disable-executable-stripping --disable-library-stripping
exit status: 1
stderr: Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
JavaScript exception: Error: spawn EBADFcabal.exe: Error: some packages failed to install:
Cabal-1.22.2.0 failed during the building phase. The exception was:
ExitFailure 1
```
I'm using GHC 7.10.1 32 bit on that machine, but I used it in one of the others and it builds correctly, so I'm guessing the problem must be either Windows being 32bit itself, or perhaps Node and MSYS2.

**Comment by luite** [comment]
I have a 32 bit Windows VM now, I'll try to reproduce this.

**Comment by luite** [comment]
Is any of the files cabal needs to run (`ghcjs`, `ghcjs-pkg`, `cpp`, `haddock` for example) on a network drive, or something else that might be unavailable?

**Comment by BethAr** [comment]
No, I'm doing the installation directly from and to the main system drive.

But now that you mention, there seems to be a problem with `gcc` in the installation in MSYS2, I seem to be unable to access it with `which gcc`, even if I remove GHC's gcc from the path. Does GHCJS require`gcc` to be available both from GHC's folder *and* MSYS's?

**Comment by luite** [comment]
GHC bundles its own `gcc` on windows, so that is probably not necessary.

I still can't reproduce it, but if you want to find out which line fails, run `ghcjs-boot` until the point of failure, then go to the installation directory ( `c:\Users\Username\AppData\Roaming\ghcjs\x86-....\ghcjs` typically), and edit the `shims\src\thread.js` file, add this line to the top:

```
#define GHCJS_NO_CATCH_MAINLOOP 1
```

And re-run the ghcjs-boot command. It should print the stack trace. Perhaps you can add some debugging info to figure out the arguments.

**Comment by BethAr** [comment]
@luite, I'm now unable to reproduce the issue as well, the only thing I did differently was that I reinstalled GHC (using minGHC). I couldn't produce more information as I can't make it fail anymore. Thanks for your attention.

**Comment by luite** [comment]
I'm getting this problem in my 32 bit Win8.1 VM now

**Comment by BethAr** [comment]
Oh, the irony! Now I can't reproduce it, but you can. Anyway, when I had the problem I was using minGHC 7.10.1, but not the version that is currently available, I think it may be the release they have from early May. Cleaning everything and installing again didn't solve the problem, including removing GHC, Cabal, all package folders and everything related to GHCJS. 

I assumed it could be something with the particular machine because it is rather old, with only 2gb of RAM. The EBADF error could imply a race condition, and I thought it could be exacerbated by the lack of performance of the system. I forgot about it for a while, and when there was a new version of minGHC, I installed it and everything worked. Sorry again for not being able to produce more information.

**Comment by luite** [comment]
I have a workaround in the `improved-base` branch that should be merged soon
