### ISSUE TITLE
-odir fails to auto-vivify module directories in the absence of -hidir

### ISSUE THREAD

**Issue by dnhgff** [ghcjs/ghcjs#344]
note: if you are experiencing this issue, it is probably best to use both -hidir and -odir at the same time. the ghc manual explicitly warns against having these output files kept in different directories. i'm not even sure how much of a bug this is but it is certainly surprising behavior

this can be reproduced with a project directory structure of `./Bob/Foo.hs` where Foo.hs contains:

```haskell
module Bob.Foo where

data Foo = Foo
```

when compiled like so with ghc

    > mkdir output
    > ghc -odir output/ --make -j Bob/Foo.hs

ghc succesfully builds and places `.hi` files under Bob and `.o` files under output/Bob

however, now running ghcjs

    > rm -r output/Bob
    > ghcjs -odir output/ --make -j Bob/Foo.hs
    [1 of 1] Compiling Bob.Foo          ( Bob/Foo.hs, output/Bob/Foo.js_o )
    
    <no location info>:
        output/Bob/Foo.js_o: getFileStatus: does not exist (No such file or directory)

**Comment by luite** [comment]
Ok I think it's best to change GHCJS to follow GHC's behaviour here

**Comment by luite** [comment]
fixed in `improved-base` branch commit 122c3f70b65e1c4732c084497d089cc77a34f6ff
