### ISSUE TITLE
Exception when running compile-time code

### ISSUE THREAD

**Issue by KevinCotrone** [ghcjs/ghcjs#349]
When building [ghcjs-vdom](https://github.com/ghcjs/ghcjs-vdom) with [ghcjs-ffiqq](https://github.com/ghcjs/ghcjs-ffiqq) as a source in the sandbox, I get the error

```
src/GHCJS/VDOM.hs:86:14:
    Exception when trying to run compile-time code:
      exported function not found: Fun {funPackage = Package {unPackage = "ghcjs-vdom-0.1.0.0"}, funModule = "GHCJS.VDOM.QQ", funSymbol = "h$$ghcjszmvdomzm0zi1zi0zi0ZCGHCJSziVDOMziQQzia11_VBcfoy"}
    Code: Language.Haskell.TH.Quote.quoteExp j " $r = null; "
```

ghc is version 7.8.4
ghcjs is on master (0.1.0)
cabal is version 1.22.3

The only things that are being done are:
```
cabal sandbox init
cabal sandbox add-source ../ghcjs-ffiqq
cabal configure --ghcjs
cabal install --ghcjs
cabal build
```

**Comment by luite** [comment]
Linker bug or problem with object file metadata probably

**Comment by KevinCotrone** [comment]
I reverted to [b1bd881e38d5091cc468080da7881a24837d9df1](https://github.com/ghcjs/ghcjs/commit/b1bd881e38d5091cc468080da7881a24837d9df1) and I'm able to compile everything. Don't know if this is helpful or not.

**Comment by luite** [comment]
I can reproduce it now, I think it's an inconsistency in the QQ object file, or it's not read back properly. I'll continue investigating tomorrow

**Comment by luite** [comment]
found the problem, fix coming

**Comment by luite** [comment]
The reason I had some trouble triggering this at first is that it only shows up if the package archive (`.js_a` file) has an older version of the object file than the `.js_o` in the `dist` subdirectory.

This change just affects the linker, object files and archives remain unchanged, so there's no need to reboot ghcjs after applying the fix.
