### ISSUE TITLE
Installation of ghcjs libraries for GHC 7.10 on OS X 10 fails

### ISSUE THREAD

**Issue by hellerve** [ghcjs/ghcjs#358]
During installation of ghcjs with the command `ghcjs-boot --dev --ghcjs-boot-dev-branch ghc-7.10` I encountered the following error:

![bildschirmfoto 2015-06-08 um 17 36 31](https://cloud.githubusercontent.com/assets/7725188/8038666/00fdd514-0e05-11e5-9975-d98fb0c68e8a.png)

It is not mentioned in the wiki article concerning bugs & workarounds for GHC 7.10. Do you have any idea what might have caused the files to not be there?

Cheers

**EDIT**: 
While trying to make a gist including the whole output, the bug vanished. I have no clue what could have happened, but I guess it is fixed now.

**Comment by luite** [comment]
It's something that happens when the primops file was preprocessed incorrectly, possibly because an earlier boot was aborted. restarting from scratch (adding `--clean` to the boot command line) fixes it. it should at some point be fixed in the booter though, since this keeps occasionally showing up.

**Comment by hellerve** [comment]
Ah, that makes sense! I did add `--clean`. The build that failed was the first one, though.

Anyway, thank you very much for the support! I am trying to port a "bigger" project to ghcjs and have not yet succeeded. The tool is up and running now, though.

**Comment by hellerve** [comment]
BTW, `cannot satisfy -package-id foo` keeps popping up. Do you know why this problem could arise?

**Comment by luite** [comment]
did you create the symlink for the user package db as described in the wiki, to work around the user package db location bug in GHC 7.10.1?

**Comment by hellerve** [comment]
*Sigh*
I should really learn how to read. Thank you again!

**Comment by hellerve** [comment]
Update: I got it working. It might interest you what I did: A fancy little Scheme, now ported [to the Web](http://zepto.veitheller.de/try). It is still in its very early alpha stages (meaning I only got it working an hour ago), but still I am very impressed.

Great job with the tool!
