### ISSUE TITLE
Haskell Source Maps

### ISSUE THREAD

**Issue by hamishmack** [ghcjs/ghcjs#36]
Currently we include the Closure Compilers source maps.  These map from the minified java back to the unminified form.  It would be nice if we also had Haskell Source maps.  These would map the unminified javascript code back to the Haskell source.

First step will be to improve the source-map package so that we can use it to write mappings (see the issue in there about VLQ values).

Next we need to output a source map from the ghcjs generator, then add support in the linker.  This would give us a source map file for each unminified bundle created by the linker that points back to the Haskell source.

For bonus points we should write a tool to combine these with the closure compiler output to create a source map that goes all the way from the minified js to the Haskell source.

**Comment by qrilka** [comment]
@luite is there any info about source maps in GHCJs other than https://github.com/ghcjs/ghcjs/wiki/GHCJS-Google-Summer-of-Code-project-ideas#source-code-maps ?
That page seems to be from year 2014 - after this ticket was closed so I guess the idea is that there is some way to have source maps even with GHC throwing away `SrcLoc`?

**Comment by wdanilo** [comment]
Actually we find the lack of source maps back to Haskell code a major problem while developing big GHCJS applications. When JS error occurs finding where it cames from is challenging and tooks a really long time from our development lifecycle. If the fix would be just to not throw locations from CORE (if that would be easily doable) that could be aweosme. Are there any other ways to get it ? @luite

**Comment by jappeace** [comment]
In reflex you can do this:

```haskell
-- | Crappy source map comments
domComment :: Dom.DomBuilder t m => Text.Text -> m ()
#ifdef Debug
domComment text = Dom.comment text 
#else
domComment _ = Dom.blank
#endif
```

Stub it out on prod compilation. You can add a deubg flag to cabal with `cabal --ghc-options "-DDebug"`
