### ISSUE TITLE
JavaScript error about goog.math.Long

### ISSUE THREAD

**Issue by cdsmith** [ghcjs/ghcjs#371]
When I run code built with the current version of GHCJS, I get this in the output:

    // translated from bytestring cbits/itoa.c
    var h$_hs_bytestring_digits = [48,49,50,51,52,53,54,55,56,57,97,98,99,100,101,102]; // 0123456789abcdef
    var h$_hs_bytestring_l10 = goog.math.Long.fromBits(10, 0);
    var h$_hs_bytestring_b10 = h$bigFromInt(10);

This generates an error in the JavaScript console that goog is not defined.

    Uncaught ReferenceError: goog is not defined(anonymous function) @ lib.base.js:91

Looks like some reference escaped from https://github.com/ghcjs/shims/blob/master/pkg/bytestring.js#L67.  I haven't seen anything not work as a result, possibly because I don't usually make any use of ByteString in CodeWorld programs.

**Comment by luite** [comment]
hmm, I haven't seen this in `improved-base`, i suspect the file inclusion order is wrong, or some dependency was somehow dropped.

**Comment by k-bx** [comment]
@luite I think I didn't use improved-base at the time. I will close this by now and will re-try all experiments from masters and improved-base once again.

**Comment by k-bx** [comment]
(oops, can't close it, will update here if any issues then)

**Comment by cdsmith** [comment]
I'm not using improved-base, as I'd got the impression it was still in-progress.  Is the master branch deprecated at this point?  If so, I can stop reporting bugs for it, and try to migrate to improved-base this weekend.

**Comment by luite** [comment]
not officially deprecated, but the plan is to replace master with improved-base after 7.10.2 has been released. improved-base requires 7.10 though, and i'm not sure how many users want to keep using 7.8. so far almost everyone seems to be ok with the 7.10 requirement.

**Comment by k-bx** [comment]
Thanks for updating on all this. Would be super-cool if master's README has this info, would help a lot.

**Comment by cdsmith** [comment]
If you don't intend to fix this in the master branch, feel free to close this.  I've moved CodeWorld to GHC 7.10.2 and the improved-base branch, so it no longer is of any importance to me.  Thanks!

**Comment by cdsmith** [comment]
This was my mistake.  As you suggested, I was including things in the wrong order, with lib.js before base.js.
