### ISSUE TITLE
--with-ghc-pkg flag

### ISSUE THREAD

**Issue by mpickering** [ghcjs/ghcjs#376]
I was trying to install ghcjs with GHC 7.10.2 RC2 by specifying the `--with-ghc` flag without success. After changing the `boot.yaml` file so that `ghc-pkg` pointed to `ghc-pkg-7.10.1.20150630` rather than the `ghc-pkg` on my PATH the build completed successfully. Maybe there should be a `--with-ghc-pkg` flag as well?

**Comment by luite** [comment]
ah good point, just an oversight

**Comment by luite** [comment]
done
