### ISSUE TITLE
"h$mainZCMainzimain is not defined" when main is a re-exported function

### ISSUE THREAD

**Issue by ryantrinkle** [ghcjs/ghcjs#377]
Using this file as the main module causes "ReferenceError: h$mainZCMainzimain is not defined": https://github.com/ryantrinkle/reflex-todomvc/blob/43bb7357f98f4a345811617086accdbb8e19cb65/src-bin/main.hs

This patch works around the issue in that case: https://github.com/ryantrinkle/reflex-todomvc/commit/7fa356dcb0d58341f5e976e269b58e7516efee79

**Comment by luite** [comment]
fix merged now

**Comment by ryantrinkle** [comment]
Thanks!
