### ISSUE TITLE
panic! (the 'impossible' happened) in splitTyConApp a1_a2IY

### ISSUE THREAD

**Issue by wuzzeb** [ghcjs/ghcjs#380]
I'm using the released GHC 7.10.2 and the improved-base branch of ghcjs (using the following commands)

```
$ git clone https://github.com/ghcjs/ghcjs.git
$ cd ghcjs
$ git checkout improved-base
$ cabal install
$ ghcjs-boot --dev --ghcjs-boot-dev-branch improved-base --shims-dev-branch improved-base
```

I was then writing some code trying to decode an Export inside a callback, and when compiling with cabal received

```
<no location info>:
    ghcjs-0.1.0-7.10.2.bin: panic! (the 'impossible' happened)
  (GHC version 7.10.2 for x86_64-unknown-linux):
	splitTyConApp a1_i8KE
```

I eventually reduced it to this small test case:

```
module A where

import Data.Typeable (Typeable)
import GHCJS.Types (JSRef)
import GHCJS.Foreign.Export (Export, derefExport)
import GHCJS.Foreign.Callback

newtype Foo a = Foo (JSRef ())
newtype Bar = Bar (JSRef ())

baz :: Typeable a => (a -> Bar) -> IO (Foo a)
baz f = do
    cb <- syncCallback1 ThrowWouldBlock $ \argRef -> do
        let arg = CbArgs argRef

        aExport <- js_CbGetA arg
        ma <- derefExport aExport
        a <- maybe (error "Hello world") return ma

        let bar = f a

        js_SetBar arg bar

    js_SetCb cb

newtype CbArgs = CbArgs (JSRef ())

foreign import javascript unsafe
    "$1.aaa"
    js_CbGetA :: CbArgs -> IO (Export a)

foreign import javascript unsafe
    "$1.bar = $2"
    js_SetBar :: CbArgs -> Bar ->  IO ()

-- | Create a class with no state.
foreign import javascript unsafe
    "null"
    js_SetCb :: Callback (JSRef () -> IO ()) -> IO (Foo a)
```

When just running `ghcjs A.hs`, there is no error.  But when running `ghcjs -O A.hs`, the panic occurs.  Since cabal defaults to using `-O`, it panics.  So it is something with optimization.  But it also seems to be releated to the foreign import javascript.  If I comment out the `js_CbGetA` function and replace it with

```
js_CbGetA :: CbArgs -> IO (Export a)
js_CbGetA = undefined
```

I can compile without a panic.

For reference, I am using 7a718363ee1584e9ae43b49679b560099df79f86 of ghcjs repo and 7d4dac56cd338d0a37de4558d77c90b4f7c854f4 of ghcjs-base repo

**Comment by luite** [comment]
Ok, must be a bug, probably some interesting type that the code generator is producing. I'll look into this.

**Comment by luite** [comment]
Ok, I can reproduce this here, thanks for the test case. The simplifier chokes on something, which explains why `-O` triggers it, possibly foreign types that GHCJS allows but GHC doesn't.

**Comment by luite** [comment]
I'll be looking into this some more. @ocharles discovered some problems in `improved-base` that convinced me that I still need to tweak the GHCJS calling convention a bit. I'll need to verify again that everything the desugarer and typechecker allow is expected by the simplifier.

**Comment by luite** [comment]
The module `GHCJS.Foreign.Callback` in `improved-base` gives a core lint error that ultimately results in this panic. I think I should be able to solve this now.

**Comment by luite** [comment]
I fixed the core lint error, but that clearly wasn't the whole story, it still panics

**Comment by luite** [comment]
I think 380a199f163a1c425d903368404fbd9681e7020a fixed this

**Comment by luite** [comment]
You need to reboot ghcjs, since the wrong core can end up in unfoldings, triggering the panic

**Comment by wuzzeb** [comment]
Awesome!  I just tried it out on react-flux (https://bitbucket.org/wuzzeb/react-flux) and the panic is gone when I switch to using GHCJS.Foreign.Export.  The main problem now is that GHCJS.Foreign.Export doesn't work :), but I made a separate pull request with the fix, https://github.com/ghcjs/ghcjs-base/pull/22
