### ISSUE TITLE
Unable to read global variable with foreign import javascript 

### ISSUE THREAD

**Issue by bitc** [ghcjs/ghcjs#381]
Somewhere in JavaScript:

``` javascript
var my_global_var = 2;
```

And in Haskell:

``` haskell
foreign import javascript unsafe
    "my_global_var"
    js_readMyGlobalVar :: IO Int
```

This doesn't seem to work. It generates code like the following:

``` javascript
function h$$pz()
{
  var a = my_global_var();
  h$r1 = a;
  return h$stack[h$sp];
};
```

If I change the ffi string to "return my_global_var" then it looks like it should work:

``` javascript
function h$$pz()
{
  return my_global_var;
};
```

But it actually gives the error during runtime: `Uncaught TypeError: c is not a function`

The only workaround I've found is to use "Number(my_global_var)"

**Comment by luite** [comment]
`my_global_var` is treated as an expression, which is the reason it works like this. it's a bit counterintuitive, so perhaps this should be changed at some point.

make it a statement by explicitly assigning it to the result placeholder:

```{.haskell}
foreign import javascript unsafe
    "$r = my_global_var;"
    js_readMyGlobalVar :: IO Int
```

**Comment by bitc** [comment]
oh, of course! I read about $r but forgot about it. Feel free to close this
