### ISSUE TITLE
Using eval in ghcjs

### ISSUE THREAD

**Issue by asilvestre** [ghcjs/ghcjs#382]
It would be great having a functionality such as [this](https://hackage.haskell.org/package/plugins-1.5.1.3/docs/System-Eval-Haskell.html) with runtime dynamic evaluation of haskell code in the browser for educational purposes for instance.

I tried to use the plugins package to use the eval functionality, the installation process tells me it can't find the Linker.h file, I tried using the extra-include-dirs flag and point it to ghcjs/include/rts/ folder but gave me other compilation issues.

It just might be that this package uses native functionality with no javascript substitute yet, but I was wondering if this problem has been proposed earlier.

Thanks!

**Comment by luite** [comment]
Running this fully client side requires compiling GHCJS and the GHC library to JavaScript and some way to load the interface and library files over the network. That's a nontrivial amount of work.

If it's acceptable that code is compiled on the server, then the `ghcjsi` branch can be used as a starting point. The REPL works by incrementally sending compiled expressions to the browser, where they can be evaluated (this could be the basis for a better tryhaskell for example).

**Comment by asilvestre** [comment]
Thank you very much I imagined such a thing would require a lot of work, and that option would work too.
