### ISSUE TITLE
ghcjs-0.1.0-7.10.2.bin: ghc no longer supports single-file style package databases 

### ISSUE THREAD

**Issue by ksmk** [ghcjs/ghcjs#386]
while executing:
ghcjs-boot --dev --ghcjs-boot-dev-branch improved-base --shims-dev-branch improved-base

I got the following: 

configure: WARNING: unrecognized options: --with-compiler, --with-hc-pkg, --with-gcc
Building integer-gmp-0.5.1.0...
Preprocessing library integer-gmp-0.5.1.0...
ghcjs-0.1.0-7.10.2.bin: ghc no longer supports single-file style package databases (dist/package.conf.inplace) use 'ghc-pkg init' to create the database with the correct format.
Failed to install integer-gmp-0.5.1.0
cabal: Error: some packages failed to install: ...

Wonder if anyone gets the same using cabal 1.22.6.0 & ghc 7.10.2

**Comment by luite** [comment]
Interesting, this was caused by a bug in older cabal libraries. is your `cabal-install` program a bit older, built against Cabal earlier than 1.22.4.0?

**Comment by ksmk** [comment]
as far as I'm concerned my ver. of cabal is 1.22.6.0

**Comment by bergey** [comment]
@ksmk When I run `cabal --version`, I get the output:

```
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library 
```

I think @luite is asking about the second line of that output.

**Comment by ksmk** [comment]
Now I get 1.22.2.0 ver. of library. Playing with cabal is pain

**Comment by ksmk** [comment]
gonna check if building with the stack is going to work

**Comment by ksmk** [comment]
have thrown away all stuff from .ghc .cabal. 
glad that it helped but the compilation took forever :)
