### ISSUE TITLE
`h$hsprimitive_memset_Word8 is not defined` with Vector.Unboxed.Mutable

### ISSUE THREAD

**Issue by quyse** [ghcjs/ghcjs#387]
The following code compiles successfully, but crashes at runtime:
```haskell
import qualified Data.Vector.Unboxed.Mutable as VUM

main :: IO ()
main = do
	v <- VUM.new 10 -- <<<<<<< here
	a <- VUM.read v 0
	putStrLn $ show (a :: Int)
```
Output:
```
uncaught exception in Haskell main thread: ReferenceError: h$hsprimitive_memset_Word8 is not defined
ReferenceError: h$hsprimitive_memset_Word8 is not defined
    at h$$m0 (XXXX/dist/build/testghcjsbug/testghcjsbug.jsexe/all.js:36967:5)
    at Immediate.h$mainLoop (XXXX/dist/build/testghcjsbug/testghcjsbug.jsexe/all.js:9798:25)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```
`VUM.replicate` fails with the same error. If I change (a :: Int) to (a :: Float), it will be missing `h$hsprimitive_memset_Float`.

I'm on latest improved-base (e7b3b0099258d0739e46b1dcefb2d2793dbbc8fd).

**Comment by luite** [comment]
Oh this should be an easy fix, missing foreign functions. They should be straightforward to implement.

**Comment by luite** [comment]
I've added the required foreign code for the `primitive` package in the `improved-base` branch.
