### ISSUE TITLE
improved-base: Mysterious runtime error for Aeson array

### ISSUE THREAD

**Issue by int-index** [ghcjs/ghcjs#392]
JavaScript:

```js
function main(o) {
  console.log(o);
}
```

Haskell:

```haskell
{-# LANGUAGE JavaScriptFFI #-}
module Main (main) where

import GHCJS.Marshal (toJSRef_aeson)
import GHCJS.Prim (JSRef)
import qualified Data.Aeson.Types as A

foreign import javascript unsafe "main($1)"
  js_main :: JSRef -> IO ()

main :: IO ()
main = do
  o <- toJSRef_aeson A.emptyArray
  js_main o
```

This fails with a runtime exception: `uncaught exception in Haskell main thread: TypeError: Cannot read property 't' of undefined`. However, if you replace `A.emptyArray` with any other non-array value (e.g. `A.Number 0`, `A.Bool True` or `A.emptyObject`), this works as expected.

**Comment by luite** [comment]
Ok that doesn't look good. I'll look into this

**Comment by int-index** [comment]
After inlining some definitions, I got a more minimal example to reproduce the bug:

```haskell
{-# LANGUAGE JavaScriptFFI #-}
module Main (main) where

import GHCJS.Prim (JSRef)
import qualified JavaScript.Array.Internal as AI

foreign import javascript unsafe "console.log($1)"
  js_main :: JSRef -> IO ()

main :: IO ()
main = do
  o <- (\(AI.SomeJSArray x) -> x) <$> AI.fromListIO []
  js_main o
```

**Comment by int-index** [comment]
Using `AI.fromList` does not trigger the bug, so I conclude the problem is due to `AI.fromListIO`.

**Comment by luite** [comment]
Found the problem, fix coming

**Comment by luite** [comment]
should be fixed now

**Comment by luite** [comment]
fix (in `improved-base`, which is the only branch where this happened anyway) merged
