### ISSUE TITLE
SIZEOF_VOID_P not set correctly

### ISSUE THREAD

**Issue by mayhewluke** [ghcjs/ghcjs#395]
When trying to install `gtk2hs-buildtools` the following error is thrown:

```
$ cabal install --ghcjs gtk2hs-buildtools
. . .
Linking dist/build/gtk2hsHookGenerator/gtk2hsHookGenerator.jsexe (Main,Paths_gtk2hs_buildtools)
Preprocessing executable 'gtk2hsC2hs' for gtk2hs-buildtools-0.13.0.4...

c2hs/base/general/Binary.hs:408:2:
     error: #error "unsupported sizeof(HsInt)"
     #error "unsupported sizeof(HsInt)"
      ^
cabal: Error: some packages failed to install:
gtk2hs-buildtools-0.13.0.4 failed during the building phase. The exception
was:
ExitFailure 1
```

I'm about as ignorant as it gets in this area but it looks like this is because `gtk2hs-buildtools` expects `SIZEOF_VOID_P` to equal either `4` or `8` and it's getting neither. (The error is thrown in [this](https://github.com/gtk2hs/gtk2hs/blob/a63e1b20ea21cc8d15f38321f837de94c9a2d874/tools/c2hs/base/general/Binary.hs#L397) conditional due to checking `SIZEOF_HSINT` which is defined [here](https://github.com/gtk2hs/gtk2hs/blob/a63e1b20ea21cc8d15f38321f837de94c9a2d874/tools/c2hs/base/general/Binary.hs#L100) as `SIZEOF_VOID_P`)

I'm not sure if this is an issue with GHCJS or if it's with `gtk2hs-buildtools`, but if it's the latter I'd be happy to report it there instead. The issue was originally reported at NixOS/nixpkgs#9175, but I double-checked it on a fresh Vagrant machine following the GHCJS Quick Start instructions for a manual install and still got the error, so it doesn't appear to be an issue with Nix.

**Comment by int-index** [comment]
You shouldn't be able to build `gtk2hs-buildtools` using `GHCJS` since it's partially written in C. Why would you want that anyway?

**Comment by mayhewluke** [comment]
Ah, the plot thickens. No clue, to be honest. It just seems to get pulled in when trying to install `ghcjs-dom`. At least, it does when installing it via Nix, but cabal doesn't seem to pull `gtk2hs-buildtools` in before building `ghcjs-dom` (it throws an error when building but that's probably because I borked something in all my tinkering around). I'll do some more digging and see what I turn up.

**Comment by peti** [comment]
This seems to be a problem in the Nix setup (hopefully fixed by https://github.com/NixOS/nixpkgs/commit/6be6397aa1affa14ad95af5c35c3456cc1a6e2a8). The `ghcjs` package set needs certain build tools, like `happy` and `alex` imported from the regular Haskell package set for some builds to succeed. `gtk2hs-buildtools` is such a tool, but it was omitted from the relevant list.

**Comment by mayhewluke** [comment]
Seems like this was indeed Nix-related (and fixed there). Thanks to all, and sorry for the kerfuffle!
