### ISSUE TITLE
ghcjs-boot fails when cloning http://git.haskell.org/packages/directory.git

### ISSUE THREAD

**Issue by ajnsit** [ghcjs/ghcjs#403]
I'm trying to install ghcjs from the git repo. When I run `ghcjs-boot --dev`, it always fails to connect to git.haskell.org. 

```
fatal: unable to access 'http://git.haskell.org/packages/directory.git/': Failed to connect to git.haskell.org port 80: Network is unreachable
Clone of 'http://git.haskell.org/packages/directory.git/' into submodule path 'boot/directory' failed
```

Curl shows me the same thing -

```
curl -v http://git.haskell.org/packages/directory.git
* Hostname was NOT found in DNS cache
*   Trying 162.242.166.62...
*   Trying 2001:4801:7825:104:4a5:7b60:ef7:cffc...
* connect to 2001:4801:7825:104:4a5:7b60:ef7:cffc port 80 failed: Network is unreachable
* Failed to connect to git.haskell.org port 80: Network is unreachable
* Closing connection 0
curl: (7) Failed to connect to git.haskell.org port 80: Network is unreachable
```

**Comment by ajnsit** [comment]
git.haskell.org is still down (when was the last time it was up?) For now, I just modified all the submodules to point to github. The modified ghcjs code is here - https://github.com/ajnsit/ghcjs

**Comment by luite** [comment]
it works from here, probably some routing problem between `git.haskell.org` and your isp.

**Comment by ajnsit** [comment]
On more investigation, looks like the problem has to do with the ipv6 address of git.haskell.org. Curl (and firefox too for that matter) uses ipv6 instead of ipv4 and it fails. It could be some ipv6 config issue on my machine or on git.haskell.org. To work around this, I had to add the ipv4 address of git.haskell.org to my /etc/hosts file.
