### ISSUE TITLE
Branch cleanup?

### ISSUE THREAD

**Issue by mgsloan** [ghcjs/ghcjs#412]
Hey!  I just accidentally build an sdist on master thinking that it would use the older base, since the improved-base branch exists.  How about we delete all the branches on the github repo except for `ghcjsi`, `old-base`, and `master`.  The branch naming for ghcjs-base and ghcjs-boot should then be consistent with `old-base` and `master`.

i can go ahead and do this if given the go-ahead.

**Comment by mgsloan** [comment]
In `ghcjs-boot`, I suppose we'll also have `old-base-ghc-7.10` instead of `ghc-7.10`

**Comment by luite** [comment]
hm, i forgot if there's anything in the other branches i'd wanted preserve, but if there is, it's probably old and broken by now, so go ahead.

**Comment by mgsloan** [comment]
Ok, branch cleanup in progress!  The idea is to make the branches mostly consistent across the repos.  Now, `ghcjs`, `ghcjs-base`, and `shims` all have `master` and `old-base`.

I hope this hasn't screwed anything up, but I think it's important to have a clear branch naming convention to avoid confusion, particularly since the build / boot process is so dependent on the branches.

Now we have the following:

* In `ghcjs`: `master`, `old-base`

  - `ghcjsi` (when booting with this branch, you'll need to specify the right branches for shims and boot)

* In `ghcjs-base`: `master` and `old-base`

  - `new-marshal` (ping @hamishmack , can this branch be deleted?)

* In `ghcjs-boot`: `master`

  - `old-base` renamed to `old-base-ghc-7.8`

  - `ghc-7.10` renamed to `old-base-ghc-7.10`

  This way, the user will be made aware that they need to pick when doing ghcjs-boot.  (I'm not going to spend a bunch of time streamlining old-base setup..)

* `shims` is untouched except:

  - I've deleted `fix32bit`, as it's two years old and this is the only commit on it: https://github.com/ghcjs/shims/commit/8e4920f1d44f5206abb26b79a77b1f64a0538217

* `ghcjs-prim` is now referenced by submodule from the `old-base` branch of ghcjs.  Ideally, we'd be able to deprecate the repo - I've added https://github.com/ghcjs/ghcjs/issues/413 about this.
