### ISSUE TITLE
RETURN_UBX_TUP2 not defined in rts.js

### ISSUE THREAD

**Issue by manyoo** [ghcjs/ghcjs#414]
When developing a reflex and reflex-dom based app, I got the this error:
uncaught exception in Haskell thread: ReferenceError: RETURN_UBX_TUP2 is not defined

The code causing the error in rts.js is:

function h$finalizeWeak(w) {
                                                               ;
    w.val = null;
    if(w.finalizer === null || w.finalizer.finalizer === null) {
        RETURN_UBX_TUP2(null, 0);
    } else {
        var r = w.finalizer.finalizer;
        h$finalizers.remove(w.finalizer);
        w.finalizer = null;
        RETURN_UBX_TUP2(r, 1);
    }
}

I find that RETURN_UBX_TUP2 is actually defined in lib/include/ghcjs/rts.h, so I've fixed the issue in the generated rts.js directly by replacing it with the actual code.  But I think this might be a bug in ghcjs need to be fixed.

**Comment by luite** [comment]
thanks, fixed, file was not getting included.
