### ISSUE TITLE
TypeError: undefined is not a function: hsprimitive_memset_Word8

### ISSUE THREAD

**Issue by Mikolaj** [ghcjs/ghcjs#415]
With Quick Start from 2 days ago I'm getting:

```
node  dist/build/LambdaHack/LambdaHack.jsexe/all.js
uncaught exception in Haskell thread: TypeError: undefined is not a function
TypeError: undefined is not a function
    at h$hsprimitive_memset_Word8 (/mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/all.js:20830:108)
    at h$$kXf (/mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/all.js:713341:5)
    at Immediate.h$mainLoop (/mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/all.js:9102:25)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
thread blocked indefinitely in an STM transaction
```

and similarly in a chromium browser (under webkit there are no problems):

```
uncaught exception in Haskell thread: TypeError: undefined is not a function rts.js:8244
TypeError: undefined is not a function
    at h$hsprimitive_memset_Word8 (file:///mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/lib.js:284:108)
    at h$$kXf (file:///mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/out.js:689062:5)
    at h$mainLoop (file:///mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/rts.js:9104:25)
    at file:///mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/rts.js:3485:25
    at runIfPresent (file:///mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/rts.js:3503:21)
    at onGlobalMessage (file:///mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/rts.js:3544:17) 
```

and the offending call  is ```h$hsprimitive_memset_Word8(c, f, b, d)``` in the following context:

```
function h$$kXf()
{
  var a = h$r1;
  var b = h$stack[(h$sp - 5)];
  var c = h$stack[(h$sp - 4)];
  var d = h$stack[(h$sp - 3)];
  var e = h$stack[(h$sp - 2)];
  var f = h$stack[(h$sp - 1)];
  h$sp -= 6;
  if(a)
  {
    h$hsprimitive_memset_Word8(c, f, b, d);
    h$l4(false, ((f + b) | 0), h$ghczmprimZCGHCziTypesziSPEC, e);
    return h$ap_4_3_fast();
  }
  else
  {
    h$r1 = f;
  };
  return h$stack[h$sp];
};
```

The test program from https://github.com/ghcjs/ghcjs/issues/387 runs OK for me and returns 0. I'd rather learn if I'm doing something silly before I try to extract a minimal failing example.

**Comment by luite** [comment]
Hmm, four arguments, the one in the JS implementation takes five. Looks likes this may be called on both `Addr#` (`Ptr`) and `ByteArray#` primitives. Can you share the code that uses this?

**Comment by luite** [comment]
Never mind, found it in `Data.Primitive.Internal.Operations`, I'll push a fix soon.

**Comment by luite** [comment]
Still I wouldn't expect this exception for this problem, so perhaps some reproducing code will be useful later.

**Comment by Mikolaj** [comment]
I've pushed the (big and messy) code to master branch of https://github.com/LambdaHack/LambdaHack. Just build with ```cabal install -fbrowser --ghcjs``` and running it you should see the exception. Without ```--ghcjs``` it (sort of) works in webkit. The code where DOM is initialized is in ```Game/LambdaHack/Client/UI/Frontend/Dom.hs```, but that's not where the exception is raised.

**Comment by luite** [comment]
the webkit js engine was missing the `fill` method which caused this problem. I've also added proper `ByteArray#` versions of the memset functions to the primitive bindings now.

**Comment by Mikolaj** [comment]
Should I reinstall via QuickStart to get these changes, or are they not yet bundled in the tar archives?

**Comment by luite** [comment]
The latest snapshot has the changes

**Comment by Mikolaj** [comment]
The bug is gone. Thank you. Closing.
