### ISSUE TITLE
Rename JSRef to JSVal?

### ISSUE THREAD

**Issue by mgsloan** [ghcjs/ghcjs#421]
I realize this is bikeshedding one of the most core types in GHCJS..  However, due to [this question](https://github.com/ghcjs/ghcjs-base/pull/34#issuecomment-145752756) I realized that the name `JSRef` can give the wrong intuitions.  Due to the similarity of the name to `IORef` / `STRef` / etc, one would think that `JSRef` is a mutable cell.  However, instead it's a JavaScript value which is one of the primitive JavaScript types.  Sure, the common case is that it's a mutable object, and so in that case "*Ref" isn't such a bad name.  Even then, though, it's a value that can be mutated and queried in a variety of ways - it's not a mutable cell.

**Comment by spl** [comment]
When I first saw it, `JSRef` did make me think of `IORef`, `STRef`, and the like. In fact, in the code base that I inherited, there was some code written in the style of `Data.IORef` for `JSRef`s. Once I realized what it was, it became clear that it is a reference of sorts. However, I do think `JSVal` is better. It also fits better with the standard JSON/Aeson naming.

**Comment by luite** [comment]
I agree with the potential confusion here, and I don't really have a good argument against the change, other than that it causes everything to break. So it's pretty much either doing it now or leaving it the way it is.

I'm leaning towards changing, but since all libraries need to be updated, I'd like to do it when I have lots of time, the hackathon next weekend should be a reasonable opportunity.

**Comment by meiersi** [comment]
I thin JSVal is a good choice and would be in favor of this change.

Luite Stegeman <notifications@github.com> schrieb am Di., 6. Okt. 2015 1:58
PM:

**Comment by jasonzoladz** [comment]
Please don't do this.  JSRef is not confusing.  It would great to have some stability, so that we can use GHCJS for real work.

**Comment by int-index** [comment]
> Due to the similarity of the name to IORef / STRef / etc, one would think that JSRef is a mutable cell.

And that's indeed what I thought initially. I think that the name change will reduce the confusion for newcomers.

**Comment by luite** [comment]
> Please don't do this. JSRef is not confusing. It would great to have some stability, so that we can use GHCJS for real work.

The rationale to do it now is that `improved-base` already has a whole bunch of breaking changes, including one to the type of `JSRef` itself (removing the phantom parameter), so it's best to bundle more things, not to think more lightly of breaking things in the future. Of course we shouldn't start aimlessly changing things... I hope that if we export `JSRef` as a synonym for `JSVal` for a while the breakage of this change is not all that bad.

I'd like to go over the base library at the hackathon next week to see if there are more opportunities to make naming better or more consistent. Suggestions welcome.

**Comment by mgsloan** [comment]
> Please don't do this. JSRef is not confusing. It would great to have some stability, so that we can use GHCJS for real work.

I understand the reservation, but as Luite points out, a lot is already changing from old-base to improved-base (master).  While such changes are unpleasant, this is 

> I hope that if we export JSRef as a synonym for JSVal for a while the breakage of this change is not all that bad.

I like this idea.  We could even go as far as:

```haskell
type JSRef a = JSVal  {-# DEPRECATED JSRef "Use JSVal instead" #-} 
```

Then old-base code will be less broken than it will be presently, and just be less typed.  Code that's already ported to improved-base will error out, but we probably want to convert those to JSVal anyway.

**Comment by jasonzoladz** [comment]
Synonym sounds great.  

My reaction was rooted in your recent work of @mgsloan on stack integration (and the react-flux library of John Lenz); that is, GHCJS is both usable and awesome.  I really want it to remain so.  :)

**Comment by mgsloan** [comment]
It sounds to me like we have enough consensus that this is a good idea.  I'll make some PRs.

**Comment by cliffordbeshers** [comment]
For your amusement: http://www.catb.org/esr/writings/taoup/html/ch15s04.html

Search for the paragraph with 'embedded base'.

**Comment by mgsloan** [comment]
I've opened a bunch of PRs.  Booting successfully sofar, but not necessarily ready yet.

**Comment by mgsloan** [comment]
Ok, it builds and a trivial `putStrLn "hello world"` works!  I haven't tested `domconv-webkit`, and `ghcjs-dom` still needs to be updated.

**Comment by luite** [comment]
Ok, since there is no strong voice against this, and the type synonym should to a decent job at keeping breakage at bay, I'd better merge this sooner than later, since this does break people's libraries once they update for the recent `JSRef` phantom removal.

Apologies to those who have already updated to phantomless `JSRef`.

**Comment by mgsloan** [comment]
Woot!
