### ISSUE TITLE
Uncaught Thread exception on page load

### ISSUE THREAD

**Issue by zopa** [ghcjs/ghcjs#429]
I'm getting "Uncaught thread aborted, exit code: 0" immediately on page load.

Stack trace:

    h$exitProcess	        @	VM101 rts.js:10014
    h$doneMain	            @	VM101 rts.js:9988
    h$doneMain_e	        @	VM101 rts.js:13925
    h$mainLoop	            @	VM101 rts.js:9775
    (anonymous function)	@	VM101 rts.js:3645
    runIfPresent	        @	VM101 rts.js:3663
    onGlobalMessage         @	VM101 rts.js:3704

The minimum haskell to reproduce is just `main = return ()`. This is with ghcjs 6591e99.

**Comment by luite** [comment]
I think this has been fixed already, with the latest shims commit: https://github.com/ghcjs/shims/commit/a750a701d1c061ad5cc6aa45ebdb239ea947c62c

**Comment by zopa** [comment]
Oh, great; I"ll bump my shims version and report back.
