### ISSUE TITLE
HTML5 Canvas support

### ISSUE THREAD

**Issue by wavewave** [ghcjs/ghcjs#43]
Although I guess HTML5 canvas support probably need a solution to javascript FFI, I would like to raise this issue for having discussion about the implementation idea.  One lightweight implementation may be to make wrappers for javascript function and organize them as a cabal package like ghcjs-dom. To make a cool example using HTML5 canvas can boost lots of interest in this project.

**Comment by luite** [comment]
built into `improved-base` branch
