### ISSUE TITLE
jsbits/xhr.js is not included in final output files

### ISSUE THREAD

**Issue by broma0** [ghcjs/ghcjs#430]
The following code compiled with `ghcjs -DGHCJS_BROWSER <file>`

    import Data.JSString
    import JavaScript.Web.XMLHttpRequest

    main = print . contents =<< xhrByteString req 
      where req = Request
                  { reqMethod          = GET 
                  , reqURI             = pack "/some/url"
                  , reqData            = NoData
                  , reqLogin           = Nothing
                  , reqHeaders         = []
                  , reqWithCredentials = False
                  }

results in the following error:

> JavaScript exception: ReferenceError: h$sendXHR is not defined

This is fixed by adding `jsbits/xhr.js` to the page. I suspect that the `xhr.js` simply isn't getting bundled up with the generated javascript.

**Comment by luite** [comment]
Should've been fixed already, at least in `ghcjs-base`, but I'm not sure if I've already bumped the `ghcjs-boot` submodule to include the fix.

**Comment by luite** [comment]
I hadn't, but now I have

**Comment by luite** [comment]
fixed
