### ISSUE TITLE
Finalizer called on live object

### ISSUE THREAD

**Issue by ryantrinkle** [ghcjs/ghcjs#450]
[This program](https://github.com/ryantrinkle/gc-issue/blob/master/Main.hs) results in a finalizer being called when the IORef it is attached to is still live.  In order to reproduce the issue, it should be built with the following options:

```bash
ghcjs Main.hs -fforce-recomp -Wall -O1 -fignore-interface-pragmas -o broken.jsexe -DGHCJS_GC_INTERVAL=-1 -DGHCJS_SCHED_CHECK="(scheduled=0,3)" -DGHCJS_SCHED_DEBUG=1 -DGHCJS_SCHED_QUANTUM=1
```

To build a similar progam that does not trigger the issue, add `-DWORKING` to the command.

Although these rather extreme command line flags are necessary to reproduce the issue reliably on a small program, the original test case was a large program that exhibited intermittent failures; it was built without any unusual command line flags.  These flags seemed to make the issue occur reliably, and allowed the test case to be brought down to a more manageable size.

**Comment by luite** [comment]
thanks, I'll look into this one

**Comment by benmos** [comment]
Could this (as-yet not merged) GHCJS WeakRef fix for Reactive Banana be relevant?  https://github.com/avieth/shims/commit/612f9bea8c41d90cd8ade13a0483a12c8990bd06

**Comment by cstrahan** [comment]
> Could this (as-yet not merged) GHCJS WeakRef fix for Reactive Banana be relevant? avieth/shims@612f9be

For reference, the corresponding PR appears to be: https://github.com/ghcjs/shims/pull/25

**Comment by ryantrinkle** [comment]
I did some more digging, and i think https://github.com/ghcjs/shims/pull/29 will fix this.  It appears that, when traversing a closure of size 13 or greater, the garbage collector missed the first entry (the d1 field), but did traverse all the other fields (in d2).  This commit just fixes the line that causes d1 to be traversed.
