### ISSUE TITLE
h$ghcjs_setLineDash is not defined

### ISSUE THREAD

**Issue by bergey** [ghcjs/ghcjs#452]
The tests for [diagrams-ghcjs](https://github.com/ghcjs/diagrams-ghcjs/) compile but fail to find `setLineDash` at runtime.

### To reproduce:

- checkout `diagrams-ghcjs` 5690faf6c3b5c70f79bd1ecfcc86fa92e94b0894
- cd to `tests`
- `make stack`
- open the `Main.jsexe/index.html` in web browser

### expected

Dashed lines rendered by `diagrams-ghcjs`, or else an error when compiling `diagrams-ghcjs`.

### got

```
uncaught exception in Haskell main thread: ReferenceError: h$ghcjs_setLineDash is not defined
rts.js:8792 ReferenceError: h$ghcjs_setLineDash is not defined
    at h$$aVg (out.js:72268)
    at h$mainLoop (rts.js:9742)
    at rts.js:3645
    at runIfPresent (rts.js:3663)
    at onGlobalMessage (rts.js:3704)
```

Let me know if I can help with debugging this.

**Comment by luite** [comment]
Oh that looks fairly simple to fix. Looks like this function imported in `JavaScript.Web.Canvas` just isn't there. I wonder if I forgot to add it to jsbits.

**Comment by bergey** [comment]
Oh, great.  I think `h$ghcjs_lineDashOffset` has the same problem - it doesn't occur in jsbits.
