### ISSUE TITLE
uncaught exception in Haskell main thread: TypeError: Cannot read property 'f' of null

### ISSUE THREAD

**Issue by ryantrinkle** [ghcjs/ghcjs#477]
The following program produces this error:

```
uncaught exception in Haskell main thread: TypeError: Cannot read property 'f' of null
TypeError: Cannot read property 'f' of null
    at h$ap_0_0_fast (/home/ryan/wrinkl/aspen/frontend/src/Main.jsexe/all.js:20397:23)
    at h$$nE (/home/ryan/wrinkl/aspen/frontend/src/Main.jsexe/all.js:37245:10)
    at h$runThreadSlice (/home/ryan/wrinkl/aspen/frontend/src/Main.jsexe/all.js:9814:11)
    at h$runThreadSliceCatch (/home/ryan/wrinkl/aspen/frontend/src/Main.jsexe/all.js:9771:12)
    at Immediate.h$mainLoop (/home/ryan/wrinkl/aspen/frontend/src/Main.jsexe/all.js:9766:9)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

```haskell
{-# LANGUAGE MultiParamTypeClasses #-}
module Main (main) where

newtype WithIndex v = WithIndex { unWithIndex :: Maybe v }

class Foldable f => FoldableWithIndex f where
  ifoldMap :: f a -> x

instance Foldable WithIndex where
  
instance FoldableWithIndex WithIndex where

class A
instance A

class B
instance B

class C
instance C

class HasIndex f where
  keysByIndex :: f a
  findValues :: (A, B, FoldableWithIndex f, C)
             => ()
             -> f b
             -> f b

instance HasIndex WithIndex where
  findValues _ wi = ifoldMap wi

main :: IO ()
main = do
  let val = WithIndex mempty :: WithIndex ()
      f = unWithIndex . findValues ()
  f val `seq` return ()
```

**Comment by cdsmith** [comment]
More data: I cannot reproduce at code.world/haskell.  That's with GHC 7.10.3, and GHCJS head as of January 30, and building with -O2 -Wall.  I get the expected runtime error:

    Qk_/Qk_pzoa51Gwcquv_oEW8xhA.hs:11:10-36: No instance nor default method for class operation ifoldMap

Are you using a different GHC?  Does -O2 matter?  Or is this a GHCJS regression that's happened since January?

**Comment by ryantrinkle** [comment]
@cdsmith Interesting!  I'm using -O0, and the error you got is exactly what I would have expected, as well - and, indeed, what i get when I eliminate A, B, or C from the list.  It seems to depend critically on the function having at least 6 arguments (including dictionaries).

**Comment by cdsmith** [comment]
Okay, I can reproduce when I compile by hand.  I'd forgotten that CodeWorld does a two-step compile to help it prebuild most of the standard library.  When I disable that, your bug still happens.

**Comment by ryantrinkle** [comment]
I just submitted https://github.com/ghcjs/ghcjs/pull/478.  @cdsmith, if you
have a chance, it would be great if you could confirm that it fixes this
issue for you.

**Comment by cdsmith** [comment]
This does fix your example for me, and it doesn't seem to break any of the pre-existing programs that I've tried.  But I do not have the knowledge of the GHCJS runtime to know whether it's the right answer or not.

**Comment by ryantrinkle** [comment]
Fixed by 689c7753f50353dd05606ed79c51cd5a94d3922a

**Comment by agocorona** [comment]
I have the exact same issue with the latest Luite release for ghc 8.0

Has this release dropped the patch 689c775 ?

If not, could we reopen the issue?

**Comment by geraldus** [comment]
Looking at [sources](https://github.com/ghcjs/ghcjs/blob/ghc-8.0/src/Gen2/RtsApply.hs#L159) I see that this patch does not suppressed in `ghc-8` branch.  This issue also happened for me with GHCJS based on GHC version 7.10.3 as well.

**Comment by luite** [comment]
Do you have a small program, preferably one module, no package dependencies other than what's installed by `ghcjs-boot`, runnable in the terminal with node.js, that exhibits the problem?

I've cherry-picked the relevant patches into the `ghc-8` branch, so this is likely a separate issue. GHC 8 was a relatively big update, so it's not too surprising that something else might have been broken.

**Comment by agocorona** [comment]
Unfortunately it is a browser program that uses a reactive library. I will try to have something
