### ISSUE TITLE
GHCJS js-sources for current cabal package come before dependency js-sources

### ISSUE THREAD

**Issue by iand675** [ghcjs/ghcjs#484]
For a project I'm working on at the moment, I've got bindings to React that are in a separate package (simply called ghcjs-react). In the primary package that generates a jsexe, I have a few files in js-sources that are 3rd-party react components that I want to import via the FFI. The problem is that the lib.js file bundles all the JS code in such a way that the current executable's js-sources come before the js files provided by build-depends. I'd argue that this is a rather surprising / unintuitive ordering. Is there a rationale for the way JS dependencies are currently ordered?

**Comment by luite** [comment]
was this also fixed by your pull request?

**Comment by iand675** [comment]
I believe so!

**Comment by luite** [comment]
good! closing this then. please reopen if something is still missing.
