### ISSUE TITLE
GHCi improvements in GHC 8.0

### ISSUE THREAD

**Issue by sumitsahrawat** [ghcjs/ghcjs#494]
`GHCi` has been improved in `GHC` 8.0, and it is now much more liberal about the code it accepts:

No `let` required:

```
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Prelude> f x = x
Prelude> :t f
f :: t -> t
```

```
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Prelude> f x = x

<interactive>:2:5: parse error on input ‘=’
```

**Comment by luite** [comment]
Thanks for the PR, but as you noticed I've been working on a GHC 8 update. I'm now working on migrating GHCJSi to the new external interpreter architecture from GHC 8. Shouldn't be long before you can use the new functionality.

**Comment by sumitsahrawat** [comment]
Thanks @luite :+1:
