### ISSUE TITLE
dlist no such remote ref

### ISSUE THREAD

**Issue by k-bx** [ghcjs/ghcjs#499]
When running:

```
ghcjs-boot --dev --ghcjs-boot-dev-branch ghc-8.0 --shims-dev-branch ghc-8.0
```

I'm getting:

```
...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/boot/scientific'...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/boot/stm'...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/boot/syb'...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/boot/tagged'...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/boot/text'...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/boot/time'...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/boot/transformers'...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/boot/unix'...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/boot/unordered-containers'...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/boot/vector'...
Cloning into '/Users/kb/.ghcjs/x86_64-darwin-0.2.0-8.0.1/ghcjs/ghcjs-boot/ghcjs/ghcjs-base'...
error: no such remote ref 7a3e13e42a8598fd749acf190af2d10e3ca70472
Fetched in submodule path 'boot/dlist', but it did not contain 7a3e13e42a8598fd749acf190af2d10e3ca70472. Direct fetching of that commit failed.
```

Would be nice if you could use some other dlist commit, maybe the one in a [ghc-8 branch](https://github.com/spl/dlist/commits/ghc-8).

Also, if you have a moment, I'd ask to relax `haskell-src-exts` in ghcjs dependency to be `< 1/18`. It built fine via `stack install --resolver nightly` this way.

Thank you!

**Comment by spl** [comment]
I'm the maintainer of `dlist`, and I've been working on it lately, so things have been changing.

I didn't expect anybody to be reference the `ghc-8` branch, which spl/dlist@7a3e13e42a8598fd749acf190af2d10e3ca70472 was previously part of but – thanks to my rebasing and general `git` history manipulation – is no longer. The branch was neither publicized nor intended for general consumption. The only [differences from `master` at that commit](https://github.com/spl/dlist/compare/master...7a3e13e42a8598fd749acf190af2d10e3ca70472) were some updates to the Travis-CI configuration. There were no changes to the package itself.

In general, I would not recommend using an arbitrary non-`master` commit in the `dlist` repository or any other repository. I have not touched the history of `master` in any way, nor would I. But I see unannounced work-in-progress branches as fair game. 😄

If you were expecting `ghc-8` to have a version of `dlist` that worked with GHC 8 when the released version did not, I'm sorry if you were misled. `dlist` did not need to be changed to work with GHC 8.

I'll soon merge spl/dlist#27 to `master` and release `dlist-0.8`. It contains a few relatively minor things, so there's no need to wait for it. You should be able to get by with `dlist-0.7.1.2` or, if you prefer, the current head of `master`, spl/dlist@a3e4aced83e27fe2350914e3bcc79a562c7a9fc3.

**Comment by luite** [comment]
okay, I'll update the submodule.

I probably chose a commit or branch a while ago when I started to port GHCJS to GHC 8, and haven't given it much thought since.

Still referring to a bunch of remote repositories is probably not an ideal solution. It has broken before, I think one of the culprits was the `aeson` package, where all commit id's were rewritten due to some change of the hg <-> git bridge. GHC has a bunch of mirrors that don't let commits disappear, so that at least the compiler stays buildable. Maybe that's a good idea here too (or perhaps we could try to reduce the deps to only those included with GHC so we can just use their mirrors)

**Comment by spl** [comment]
@luite:

> Still referring to a bunch of remote repositories is probably not an ideal solution. It has broken before, I think one of the culprits was the aeson package, where all commit id's were rewritten due to some change of the hg <-> git bridge. GHC has a bunch of mirrors that don't let commits disappear, so that at least the compiler stays buildable. Maybe that's a good idea here too (or perhaps we could try to reduce the deps to only those included with GHC so we can just use their mirrors)

Is ghcjs/ghcjs-boot#35 related to this?

**Comment by luite** [comment]
I've changed the submodule to the current master with the merged changes, but I suspect the version number still needs to be bumped?

Having our own forks does make it much easier to have reliable upstream deps, but I'm still a bit hesitant since I'm not too fond of having to maintain a bunch of forks. Still it's probably better than what we have now. In the past I used the large amount of uncommited code in the GHC 8 port I was working on as an excuse to put off this change, but now that's all on github, I should probably make this change, or find another excuse ;)

**Comment by spl** [comment]
@luite Are referring to the spl/dlist@42e99cdd2d86f790fd346d20222f2d75815db567?

**Comment by k-bx** [comment]
@luite not at my computer to check the changes yet, but since you're here already — please also merge this change in ghc-8 branch

**Comment by luite** [comment]
Oh I've only changed this in the `ghc-8.0` branch of `ghcjs-boot`. I meant that the submodule reference is pointing to `master` of `dlist` now.

Unfortunately I just found out that I can't yet bump the submodule to include the new `dlist-0.8` commit, since `bytestring` doesn't accept it.

**Comment by spl** [comment]
@luite You should be fine pointing to spl/dlist@be302776fbc6853e905e3a9d74fd10b7bb3f3345 (0.7.1.2). There is most likely nothing that 0.8 will give you. The only thing that might possibly affect you is the addition of the `Semigroup` instance in 0.8.

**Comment by spl** [comment]
FYI: haskell/bytestring#84

**Comment by k-bx** [comment]
@luite great, thank you! I believe this can be closed now as it is resolved. Also, if you have 5 mins, please merge master->ghc-8 in order to have `haskell-src-exts` dependency bumped in this branch, as mentioned before it'll help using stack nightly (and reuse whole bunch of prebuilt packages) to build the ghcjs. Thank you!
