### ISSUE TITLE
http://ghcjs.luite.com/ghc-8.0.tar.gz

### ISSUE THREAD

**Issue by tolysz** [ghcjs/ghcjs#506]
Hi the ghc-8.0.tar.gz bundles from the http://ghcjs.luite.com are missing an important file: 

https://github.com/ghcjs/ghcjs/blob/ghc-8.0/src-bin/haddock/ResponseFile.hs

**Comment by luite** [comment]
hmm, I thought I had fixed this, that'd be an error in the cabal file

**Comment by luite** [comment]
fixed now

**Comment by tolysz** [comment]
I will close it once I observe the addition ;) (or you can close once you force the push)

**Comment by tolysz** [comment]
Nice :)
