### ISSUE TITLE
ghcjs-boot would apparently benefit from parallel builds

### ISSUE THREAD

**Issue by cdsmith** [ghcjs/ghcjs#514]
Here's a breakdown of the time spent running the codeworld install script.  (Ignore the gap between node.js and ghcjs-boot... this was me screwing up, resulting in ghcjs-boot failing and needing to be rerun.)

![er9bhk1gfok](https://cloud.githubusercontent.com/assets/544744/18236951/89a46892-72e0-11e6-8fde-0b63c22fbbdf.png)

The two real pain points are: (a) installing node.js, which is hard to do much about except wait for Debian to package a recent enough version, and (b) ghcjs-boot.  They both use only 1 CPU, making them take much longer than, e.g., the parallel build for GHCJS itself (due to cabal-install).

Is it possible that ghcjs-boot could prepare everything, and then install it in one `cabal install` command, which would build it in parallel as much as possible?

**Comment by luite** [comment]
The way GHCJS needs to be invoked changes during the boot process, so `ghcjs-boot` calls `cabal install` a few times, but each step does install multiple packages. Pass `-jN` to `ghcjs-boot` for parallel installs (it used to be a bit unreliable, but the last time I've seen issues with this is a long time ago. let me know if you run into any problems)

**Comment by cdsmith** [comment]
Ah, great.  I wasn't aware that ghcjs-boot accepted a flag for that.  I'll try this, and report back if it doesn't work. :)
