### ISSUE TITLE
Feature request: -s runtime option (Summary GC statistics)

### ISSUE THREAD

**Issue by Mikolaj** [ghcjs/ghcjs#516]
If that's easy, it would be great to get on stderr (termin with node, console in browser) similar output as ghc gives with -RTS -s +RTS. I tried the following in .cabal

```
    ghcjs-options:    "-with-rtsopts=-s"
```

and it's ignored, so I assume this is not available right now.

**Comment by luite** [comment]
Hmm, that's rather platform-specific to implement, since the JS GC is being used. node.js would probably let us know a bit of GC statistics, but I'm not sure about browsers.

**Comment by Mikolaj** [comment]
OK, never mind, I will use the JS tools for that, in particular your Electron integration looks promising. Closing.

**Comment by Mikolaj** [comment]
Yay, https://github.com/ghcjs/ghcjs/tree/ghc-8.6/utils/ghcjs-node-profiling is even more relevant! Will try that, too.
