### ISSUE TITLE
Crash on iOS 10 WebKit

### ISSUE THREAD

**Issue by tlaitinen** [ghcjs/ghcjs#518]
```haskell
import Control.Concurrent (threadDelay)
main = do
    threadDelay 50000
    putStrLn "fuu"
    main
```

After a while, the browser reloads the page and says "A problem occurred with this web page, so it was reloaded." and "WebKit encountered an internal error.".

The crash does not occur when USB cable is attached and Web inspector is in an active debugging session.

**Comment by tlaitinen** [comment]
Also crashes with Safari Technology Preview.
[crash.txt](https://github.com/ghcjs/ghcjs/files/487013/crash.txt)

**Comment by cstrahan** [comment]
Wow, that's exciting. :)

**Comment by luite** [comment]
Hmm, interesting. I don't seem to get a crash with Safari 10 on OS X 10.8.6, with GHCJS on 7.10.3.

Can you perhaps upload the jsexe somewhere so we can rule out compiler version differences?

**Comment by tlaitinen** [comment]
I reported the bug at https://bugs.webkit.org/show_bug.cgi?id=162388 and the test case is available at http://www.feriko.fi/example/ and https://bugs.webkit.org/attachment.cgi?id=289557 .

I got the crash using Safari Technology Preview (Safari 10.0, WebKit 11603.1.5). If Web Inspector is open, the crash may not necessarily occur.

**Comment by tlaitinen** [comment]
nope

**Comment by tlaitinen** [comment]
Based on the stack trace, the crash seems to occur in the JIT compiler, so I googled for ways to disable the JIT. I found this http://stackoverflow.com/questions/13147026/disabling-jit-in-safari-6-to-workaround-severe-javascript-jit-bugs which suggested to use try-catch blocks.

The problem does not occur if I modify the function h$startMainLoop slightly by wrapping the body of the loop in a try-catch block:

```javascript
function h$startMainLoop() {                        
                                                    ;
    if(h$running) return;
    
    if(typeof setTimeout !== 'undefined') {
        
        if(!h$mainLoopImmediate) {
            h$clearScheduleMainLoop();
            h$mainLoopImmediate = setImmediate(h$mainLoop);
        }
    
    } else {
        while(true) {
          try { // BEGIN WRAP
            h$mainLoop();
          } catch (e) {throw e;} // END WRAP
        }
    }
}
```
The test case with the modification above is available at http://www.feriko.fi/example3/ . 

PS. Also in the weird things department, Chrome crashes on iOS 10.0.2 but not Dolphin browser (which should use the same WebKit...).

**Comment by luite** [comment]
hmm, that's interesting. in browsers setTimeout should really be defined, so this path shouldn't even be taken.

Since the actual scheduling of the main loop is done indirectly, this shouldn't have much performance impact. I'll do a bit more testing to be sure though.

**Comment by luite** [comment]
the workaround is in the `shims` repo. if anyone stills sees crashes, please report here.

**Comment by luite** [comment]
I hope the lack of more complains means that the fix worked. Thanks for investigating and providing the code!
