### ISSUE TITLE
Unhandled primop: CopyByteArrayToAddrOp

### ISSUE THREAD

**Issue by FPtje** [ghcjs/ghcjs#523]
After playing around with a ghcjs branch of servant-client, I came across the issue described in this post:
https://github.com/haskell-servant/servant/issues/51#issuecomment-250737727

(See the section called FormURLEncoded)

After narrowing down the culprit, I've created the following minimal working example:

```haskell
{-# language BangPatterns #-}
{-# language OverloadedStrings #-}
module Main where

import Data.ByteString.Builder (toLazyByteString, shortByteString, string8)

main :: IO ()
main = do
  putStrLn "Testing the ghcjs 'unhandled primop' error"

  -- Reproduces the issue
  putStrLn "step 1"
  let !step1 = shortByteString "hello"
  putStrLn "step 2"
  let !step2 = toLazyByteString step1

  return ()
```

A full project, including a server that runs this example can be found [here](https://github.com/LumiGuide/servant-client-ghcjs-problemCauser).

Running this code will have the browser throw the following exception:

```
uncaught exception in Haskell main thread: unhandled primop: CopyByteArrayToAddrOp (0,5)
```

# Cause
`shortByteString` calls `Data.ByteString.Short.Internal.copyToPtr` which in turn calls `copyByteArrayToAddr`. That's the direct source of the error.

This issue has been tested on ghcjs-0.2.0 with ghc 7.10.3.

**Comment by FPtje** [comment]
Note: This error is also described in [this fpco/store issue](https://github.com/fpco/store/issues/43)

**Comment by luite** [comment]
I've added the primops, can you check if this helps?

**Comment by FPtje** [comment]
That solves it.
