### ISSUE TITLE
Document Foreign Function Interface(FFI).

### ISSUE THREAD

**Issue by crocket** [ghcjs/ghcjs#525]
I tried reading

- https://github.com/ghcjs/ghcjs/wiki/A-few-examples-of-Foreign-Function-Interface
- https://github.com/ghcjs/ghcjs-base/blob/master/GHCJS/Foreign/Internal.hs
- http://weblog.luite.com/wordpress/?p=14.

I still don't understand FFI much. I leave a reminder here so that anyone who knows GHCJS better than I do remembers to document FFI somewhere.

I think it would be ideal to document FFI on https://github.com/ghcjs/ghcjs/wiki/GHCJS-User-Guide#interacting-with-javascript

**Comment by joehealy** [comment]
@crocket I got a long way with GHCJS.Marshall and toJSVal

for plotting with flot, I am currently (still very basic using the following):

foreign import javascript unsafe "mplot($1, $2)" jqPlot' :: GT.JSString -> GT.JSVal -> IO ()


jqPlot :: String -> [[Maybe (Double, Double)]] -> IO ()
jqPlot n vs = toJSVal vs >>= jqPlot' (GDT.toJSString n)

**Comment by spl** [comment]
(Off-topic)

@joehealy: I've got some Flot code lying around. It's currently in a proprietary package, but I'm pretty sure my colleague wouldn't mind open-sourcing it. Do you have more than that? Is it worth creating a package with mine and/or yours?

**Comment by crocket** [comment]
@joehealy Thanks, but that's not enough to understand FFI comprehensively.

@luite I think you're in the best position to document FFI or help me document FFI on https://github.com/ghcjs/ghcjs/wiki/GHCJS-User-Guide#interacting-with-javascript or somewhere else. Can you help us?

**Comment by crocket** [comment]
@joehealy Thanks, but that's not enough to understand FFI comprehensively.

@luite @hamishmack I think you're in the best position to document FFI or help me document FFI on https://github.com/ghcjs/ghcjs/wiki/GHCJS-User-Guide#interacting-with-javascript or somewhere else. Can you help us?

I'd like to have FFI and marshalling documented.

**Comment by luite** [comment]
yeah that document is in need of some attention. There is a bit of documentation in various places in various states of outdatedness. I think I'll make a start by collecting some of it, and add it there.

For a reference guide, the marshalling code is probably a separate topic, since it adds some convenience on top of the JavaScriptFFI. But it will often be used together. Perhaps we should also have a handbook type doc with examples of how to do common tasks, pointing to performance pitfalls etc?

**Comment by crocket** [comment]
@luite Actually, I had a few intensive Q&A sessions about Javascript FFI with hamishmack on gitter. And, I'm preparing a pull request for FFI documentation. Since my focus is currently on FFI documentation, I'll be faster. I hope my pull request was merged quick and people fixed it after merging it.

**Comment by luite** [comment]
Great I'll wait for that PR.
