### ISSUE TITLE
Error: h$zlibVersion is not defined

### ISSUE THREAD

**Issue by hansroland** [ghcjs/ghcjs#532]
In GHCJS I try to create images with JuicyPixels and display them with a  \<img src="data:image/png;base64,...> HTML/DOM element.

When I try to create the base64 string, I get the *h$zlibVersion is not defined* error.

Here is the (simplified) code:
~~~
module Main where
import Codec.Picture

main :: IO ()
main = putStrLn $ encodePng myImage

myImage = generateImage pixelRenderer 250 300
  where 
    pixelRenderer x y = PixelRGB8 (fromIntegral x) (fromIntegral y) 128
~~~

This is the error message in the browser console:
~~~
uncaught exception in Haskell main thread: ReferenceError: h$zlibVersion is not defined
rts.js:8840 ReferenceError: h$zlibVersion is not defined
    at h$$H7 (out.js:33353)
    at h$runThreadSlice (rts.js:9838)
    at h$runThreadSliceCatch (rts.js:9795)
    at h$mainLoop (rts.js:9790)
    at rts.js:3670
    at runIfPresent (rts.js:3688)
    at onGlobalMessage (rts.js:3729)
~~~

Version: The Glorious Glasgow Haskell Compilation System for JavaScript, version 0.2.0 (GHC 7.10.3)

**Comment by luite** [comment]
JuicyPixels uses the zlib bindings for the PNG deflate compression. These use `foreign import ccall` to call into C library. There is no port to JS yet.

Adding a direct port of the C functions might be the most straightforward, but it probably doen't result in optimal performance. Perhaps `JuicyPixels` could use built-in functionality of the platform to encode a PNG if available? (for browser I'm thinking of `Canvas` and `toDataURL` or `toBlob`)

**Comment by hansroland** [comment]
Uhh, Sorry! I assumed JuicyPixel would be *pure* Haskell...

I'm pleased to tell you, that encoding the picture as a bitmap with **encodeBitmap** instead of *encodePng* works perfectly!

Many thanks for looking into it.
