### ISSUE TITLE
Support for -ddump-hi?

### ISSUE THREAD

**Issue by mgsloan** [ghcjs/ghcjs#533]
Stack uses `-ddump-hi` along with `-ddump-to-file`, in order to detect unlisted modules, and possibly more features in the future.  These options don't seem to work with ghcjs - see https://github.com/commercialhaskell/stack/issues/2341

**Comment by luite** [comment]
hmm, it should work, probably a bug.

**Comment by luite** [comment]
Can you give an example of a ghcjs invocation that goes wrong? I just did a simple test with `-ddump-hi` `-ddump-to-file` with some haskell files in the same dir, and I do get `.dump-hi` files.

Perhaps it writes them to the wrong place in more complicated scenarios?

**Comment by mgsloan** [comment]
Thanks for looking into it @luite , my mistake, though.  Turns out the issue was passing `--ghc-options` into Cabal rather than `--ghcjs-options`.

**Comment by luite** [comment]
Hmm, might be a problem in cabal then: cabal should actually also respect ghc options for ghcjs, as a derived compiler. At least this was the original plan.

**Comment by mgsloan** [comment]
Right, that would make sense to me.  This is with `Cabal-1.22`.  @nh2 opened an issue recently on the topic - https://github.com/haskell/cabal/issues/3999
