### ISSUE TITLE
Create a gitter channel for this repository.

### ISSUE THREAD

**Issue by crocket** [ghcjs/ghcjs#534]
IRC is inconvenient because it lacks backlog and various other functionalities that gitter or slack has.

I'd like to ask questions in a gitter channel, modify my messages, come back later to read backlog, share snippets, etc, ...

I am not suggesting that everyone on #ghcjs on freenode should move to a gitter channel.
But, I'd like to be in a gitter channel for ghcjs/ghcjs. Other people can test gitter and decide whether or not to stay on it.

**Comment by schell** [comment]
@crocket - there's always http://ircbrowse.net/ghcjs and lambdabot's @tell functionality :)

**Comment by crocket** [comment]
That's better, and it might be better than gitter in some aspects. But, in my point of view, it doesn't subsitute gitter.

**Comment by mgsloan** [comment]
I agree that this would be nice to have, these days I prefer gitter or slack over raw IRC.

**Comment by crocket** [comment]
It is now available at https://gitter.im/ghcjs/Lobby

**Comment by schell** [comment]
👍
