### ISSUE TITLE
Incremental Linking with Stack and GHCJS

### ISSUE THREAD

**Issue by mchaver** [ghcjs/ghcjs#538]
https://github.com/ghcjs/ghcjs/wiki/Deployment#multiple-pages--incremental-linking

Is there a way to do incremental linking if you are compiling with stack? I've been trying various ways to pass options but I haven't been successful yet.

**Comment by elfeck** [comment]
I am also interested in this. @mchaver if you find anything out please let me know here.

**Comment by mchaver** [comment]
@elfeck 

It's actually pretty simple, but it took me a while to figure it out. I have a simple example you can refer to here, just follow the readme:

https://github.com/plow-technologies/ghcjs-test-stack-linking

I was able to get it working with more complicated code.

**Comment by elfeck** [comment]
Thanks a lot for the example!
