### ISSUE TITLE
When accessing multiple fields from a record: uncaught exception ReferenceError

### ISSUE THREAD

**Issue by adarqui** [ghcjs/ghcjs#558]
Ok so, I don't have any simple code to reproduce this.. It's a very weird bug that i'm experiencing in my (large) code base - which uses ghcjs + react-flux. This could vary well be related to react-flux, but i've never gotten a response from the author. However, I have spoken to luite on freenode #ghcjs and he was able to download all of my code and reproduce it locally. He stated he would investigate it but i've never heard back - I imagine he is busy.

So with that said, and my limited knowledge of Haskell .. i'm just posting an issue and maybe @luite could even fill in some details of his findings if he sees this.

Long story short, here's what i'm experiencing. I have an app (forum) with tons of records.. Eventually, I run into an issue where I can't use multiple fields from a record or the code breaks with an error like this:

all.min.js?1482903977.675248s:10068 uncaught exception in Haskell thread: ReferenceError: h$$z35UjYqEQYfzzNbGHdh8dVwG3MZCLNziUIziReactFluxziAppziThreadPostsziww136_XKcgdI is not defined
all.min.js?1482903977.675248s:10068 ReferenceError: h$$z35UjYqEQYfzzNbGHdh8dVwG3MZCLNziUIziReactFluxziAppziThreadPostsziww136_XKcgdI is not defined

I can use the record & multiple fields from the record elsewhere. So out of nowhere, as perhaps the accumulation of the weight of the code, I reach a spot where I can't use multiple fields from a record.

Here's an example. The first code used to work, but, after the code grows, it stops working. I'm using multiple fields from a ThreadPostStatResponse field:

```
viewPostStats
  :: ThreadPostStatResponse
  -> HTMLView_

viewPostStats !stat =
   showTableClean
     []
     ["score", "up", "neutral", "down", "stars", "views"]
     [[threadPostStatResponseLikes - threadPostStatResponseDislikes]
     ,[threadPostStatResponseLikes]
     ,[threadPostStatResponseNeutral]
     ,[threadPostStatResponseDislikes]
     ,[threadPostStatResponseStars]
     ,[threadPostStatResponseViews]
     ]
    where
    ThreadPostStatResponse{..} = stat
```

So that used to work.. And now, the only way I can get my app to work, is to only use one field from that record, in that spot of the app:

```
viewPostStats
  :: ThreadPostStatResponse
  -> HTMLView_

viewPostStats !stat =
   showTableClean
     []
     ["score", "up", "neutral", "down", "stars", "views"]
     [[0]
     ,[threadPostStatResponseLikes]
     ,[0]
     ,[0]
     ,[0]
     ,[0]
     ]
   where
   ThreadPostStatResponse{..} = stat
```

And finally, as one last example, this breaks (notice the Dislikes field also being used, multiple fields causing the app to break):

```
viewPostStats
  :: ThreadPostStatResponse
  -> HTMLView_

viewPostStats !stat =
   showTableClean
     []
     ["score", "up", "neutral", "down", "stars", "views"]
     [[0]
     ,[threadPostStatResponseLikes]
     ,[threadPostStatResponseDislikes]
     ,[0]
     ,[0]
     ,[0]
     ]
   where
   ThreadPostStatResponse{..} = stat
```

Finally, this exact same issue eventually pops up elsewhere.. Completely different code but the same issue of 'using multiple fields' from a record causing a crash.

Has anyone ever experience anything like this? Or maybe has an idea of what could be going on?

I wish I had more details and a way of reproducing with a small example, but I don't.. That's why i've never posted an issue to github... but I guess now i'm a bit desperate since I haven't really been able to work on my project for months :/ It took @luite quite a bit of time to compile my code base on his VM, but he was able to reproduce it locally with ghcjs 7.8 I think, which is what i'm using.

i dno..

Thanks

**Comment by adarqui** [comment]
Fixed by completely removing GHCJS and never using it again. Hope this solution helps people in the future.

**Comment by 3noch** [comment]
Did you ever try GHCJS 8.*?

**Comment by dmjio** [comment]
It's not conclusive that ghcjs is to blame. Are you positive the client isn't referencing an old version of that record, where that field was not defined? @adarqui
