### ISSUE TITLE
Using Compiler GHCJS with Cabal New-* Does Not Produce Correct Result

### ISSUE THREAD

**Issue by Rizary** [ghcjs/ghcjs#577]
I've posted the issue on cabal in here:

https://github.com/haskell/cabal/issues/4434

So, I want to know whether it is due to GHCJS way of built package that caused it, or maybe due to the reflex or reflex-dom library which i'll post it also there later.

**Comment by jparklev** [comment]
Did you ever resolve this?

**Comment by rizary** [comment]
see https://github.com/haskell/cabal/issues/4434#issuecomment-431561839
