### ISSUE TITLE
GHCJS-0.2.1.9007019 crashes with Data.Kind's Type

### ISSUE THREAD

**Issue by mageshb** [ghcjs/ghcjs#580]
With the following code,

```haskell
import Data.Kind

data Bar = Bar Type Type

-- data Foo = Foo (*) (*)   -- Even this doesn't work
```

I'm getting this error
```
primTypeVt: unrecognized primitive type: ghc-prim:GHC.Prim.TYPE
CallStack (from HasCallStack):
  error, called at src/Gen2/ClosureInfo.hs:214:19 in ghcjs-0.2.1.9007019-FU0Wq6nrcW4E423MvmDWR5:Gen2.ClosureInfo
```

**Comment by mckeankylej** [comment]
Also encountered this you can make the example even smaller
```haskell
import Data.Kind
data Bar = Bar Type
```

**Comment by andrewthad** [comment]
I'm running into this problem as well in a project I'm working on.

**Comment by mstksg** [comment]
I too am encountering this issue.  Is there a version of ghcjs I can use that doesn't run into this?

**Comment by mageshb** [comment]
It's blocker for me to compile one of my packages with ghcjs. Unfortunately I am not aware of any version that fix this problem.

**Comment by mstksg** [comment]
@mageshb not sure if you are pinged by the reference, but I've managed to get a version of ghcjs (#587) that might work with this.  ran a few tests and it seems to be okay, but it still hasn't been looked over by the big bosses yet.

**Comment by andrewthad** [comment]
Is there anything blocking this from being merged into GHCJS? This would be a very helpful fix.

**Comment by hamishmack** [comment]
Merged
