### ISSUE TITLE
'singletons' library TH does not compile on ghc-8.0 branch (fd:12: hPutBuf: illegal operation (handle is closed))

### ISSUE THREAD

**Issue by mstksg** [ghcjs/ghcjs#588]
Installing `singletons-2.2` using `ghcjs-0.2.1_ghc-0.8`, and the result is:

```
    (.. all business as usual)
    [46 of 50] Compiling Data.Singletons.Prelude ( src/Data/Singletons/Prelude.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0_ghcjs/build/Data/Singletons/Prelude.js_o )
    [47 of 50] Compiling Data.Promotion.Prelude.List ( src/Data/Promotion/Prelude/List.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0_ghcjs/build/Data/Promotion/Prelude/List.js_o )
    Linking Template Haskell (Data.Promotion.Prelude.Base,Data.Promotion.Prelude.Bool,Data.Promotion.Prelude.Either,Data.Promotion.Prelude.Enum,Data.Promotion.Prelude.Eq,Data.Promotion.Prelude.Maybe,Data.Promotion.Prelude.Ord,Data.Promotion.Prelude.Tuple,Data.Singletons,Data.Singletons.CustomStar,Data.Singletons.Decide,Data.Singletons.Deriving.Bounded,Data.Singletons.Deriving.Enum,Data.Singletons.Deriving.Infer,Data.Singletons.Deriving.Ord,Data.Singletons.Names,Data.Singletons.Partition,Data.Singletons.Prelude,Data.Singletons.Prelude.Base,Data.Singletons.Prelude.Bool,Data.Singletons.Prelude.Either,Data.Singletons.Prelude.Enum,Data.Singletons.Prelude.Eq,Data.Singletons.Prelude.Instances,Data.Singletons.Prelude.List,Data.Singletons.Prelude.Maybe,Data.Singletons.Prelude.Num,Data.Singletons.Prelude.Ord,Data.Singletons.Prelude.Tuple,Data.Singletons.Promote,Data.Singletons.Promote.Defun,Data.Singletons.Promote.Eq,Data.Singletons.Promote.Monad,Data.Singletons.Promote.Type,Data.Singletons.Single,Data.Singletons.Single.Data,Data.Singletons.Single.Eq,Data.Singletons.Single.Monad,Data.Singletons.Single.Type,Data.Singletons.SuppressUnusedWarnings,Data.Singletons.Syntax,Data.Singletons.TH,Data.Singletons.TypeLits,Data.Singletons.TypeLits.Internal,Data.Singletons.TypeRepStar,Data.Singletons.Util,ThRunner29)
    fd:12: hPutBuf: illegal operation (handle is closed)
```

**Comment by dmjio** [comment]
This *might* be related to the `node` version. Since `TH` w/ `ghcjs` is run via `node` iirc. If you use `nix`, it will pull in its own version. Can compile `singletons` fine like this:

```bash
λ nixos ~ →  nix-shell -p 
   "haskell.packages.ghcjsHEAD.ghcWithPackages (pkgs: with pkgs; [ singletons ])" 
```

```bash
[nix-shell:~]$ ghcjs-pkg list | grep singletons
    singletons-2.2
```

Uses `ghcjs-0.2.1-8.0.2.`

Otherwise, I have no idea.

**Comment by mstksg** [comment]
Looks like I just needed a stack clean for some reason!  I'll close this tentatively for now :)  thanks for the help!

**Comment by fisx** [comment]
this also happens to us sporadically, and it feels like a resource exhaustion issue.  only happens on the ci; re-running has always solved the problem so far.

**Comment by divipp** [comment]
`hPutBuf: illegal operation (handle is closed)` with TH is also present in #601

**Comment by luite** [comment]
I also see this problem here now.

I suspect the handle is closed by a finalizer, so repeatedly running `cabal build` eventually finishes building the package, but that's a workaround at best.

I'll dig a bit deeper to try and find the actual cause.

**Comment by luite** [comment]
I also get the issue where it eats all memory now from time to time, which unfortunately causes my laptop (macOS 10.12.6) to completely freeze and reboot.

I hope I can reproduce it in a similar way on linux, otherwise this is going to be a pain to debug...

**Comment by luite** [comment]
I think I know what's leading to the `handle is closed` error: the TH runner keeps consuming more memory until it reaches the keep alive limit. Then the process is stopped but not properly removed from the pool of available worker processes.

Maybe there's another underlying issue that causes the excessive memory consumption.

**Comment by luite** [comment]
I think eb8670c4b03b4a0ff5dd7ac3f524b410b37051ea fixes the `handle is closed` error.

**Comment by fisx** [comment]
thanks!  we're in the middle of switching from stack to nix for ghcjs and will report back once we can build and use this patch.

**Comment by fisx** [comment]
It looks like eb8670c solves our problem.  Thanks again!
