### ISSUE TITLE
Arguments empty when executing external processess

### ISSUE THREAD

**Issue by nomeata** [ghcjs/ghcjs#606]
When executing an external process, the argument actually passed to the `execve` sys call is `""`, no matter what I have in the code:
```
$ cat Test.hs 
import System.Process
main = rawSystem "echo" ["first_argument"]
/tmp $ ghcjs -O Test.hs 
[1 of 1] Compiling Main             ( Test.hs, Test.js_o )
Linking Test.jsexe (Main)
/tmp $ node Test.jsexe/all.js

/tmp $ 
```
Affects Cabal: https://github.com/haskell/cabal/issues/4742#issuecomment-327163903

This is ghcjs, `ghc-8.0` branch, bootstrapped a week ago, and node v6.11.2.

**Comment by luite** [comment]
I saw this problem for the first time last week with a Cabal setup script.

I'm pretty sure that this used to work, but I haven't had time to investigate yet. Are you using linux?

**Comment by nomeata** [comment]
Yes, Debian unstable.

**Comment by nomeata** [comment]
As an additional data point: I have also seen it on Travis, with
 * Ubuntu Trusty, 
 * Node 7.4
 * ghcjs from http://ghcjs.luite.com/master-20160628.tar.gz

The common theme is a recent version of node? Did you yourself upgrade node last week?

**Comment by cocreature** [comment]
I have been experiencing the same problem on Archlinux with `node v8.4.0` but weirdly enough only with the `ghcjs` that I’ve bootstrapped manually. `ghcjsHEAD` from `nixpkgs` as well as a version bootstrapped via `stack` from `http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz` seem to work just fine for me on the same system. While `nix` ships its own version of node, `stack` should be using the globally installed version on my system which seems to suggest that maybe node is not the problem here.

**Comment by luite** [comment]
Okay it's more widespread than I initially thought then. I was trying to build something on a fresh macOS install with a new `node.js` and thought it might be just macOS.

I'll check linux with a newer node.js

**Comment by luite** [comment]
this should be fixed in ghcjs/shims@85395dce971e23a39e5f93af4ed139ca36d4e448

**Comment by nomeata** [comment]
May not be fully fixed. At least I still observe worrisome error messages like
```
looking for tool hsc2hs near compiler in /home/travis/.cabal/bin
found hsc2hs in /home/travis/.cabal/bin/hsc2hs-ghcjs
/home/travis/.cabal/bin/hsc2hs-ghcjs --version
Warning: cannot determine version of /home/travis/.cabal/bin/hsc2hs-ghcjs :
""
```
when trying to boot ghcjs. This is using `http://ghcjs.luite.com/ghc-8.0-20170916.tar.gz` which presumably contains `ghcjs/shims@85395dc`, right?

**Comment by nomeata** [comment]
That seems to work, thanks!
