### ISSUE TITLE
fatal: program node is required but could not be found at node

### ISSUE THREAD

**Issue by RamiroPastor** [ghcjs/ghcjs#615]
Hi, first of all greetings to @luite , i met him this summer in the Utrecht Summer School!

Ok, noob question here then:

I want to start using the [miso](https://github.com/dmjio/miso) framework, and i have some installation problem while following the [README](https://github.com/dmjio/miso/blob/master/README.md) steps for stack.

I started with `mkdir app && touch app/{Main.hs,app.cabal,stack.yaml} && tree ap` and modified those 3 files as suggested. 
I then ran `stack setup` and after a while i got:

```
WARNING: Installation path /home/ramiro/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/bin not found on the PATH environment variable
Installed GHCJS.
fatal: program node is required but could not be found at node
Booting GHCJS (this will take a long time) ...Process exited with ExitFailure 1: /home/ramiro/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin/ghcjs-boot --clean
```

I then proceeded to install node.js with

```
    sudo apt-get update
    sudo apt-get install nodejs
    sudo apt-get install npm
```

But that did not solve the problem (still getting that error above).
If i run `nodejs -v` i get v4.2.6

Running `node` gives me
```
node
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
```

I have not tried that.

Also, it should be related to

> Some distros install node.js as nodejs instead of node. Add --with-node nodejs to the ghcjs-boot command in that case.

But as i'm not booting ghcjs directly, i dont know what to do :(

**Comment by ddssff** [comment]
I think nodejs-legacy just creates a link called /usr/bin/node -> nodejs, which you need.

**Comment by RamiroPastor** [comment]
Thanks, that worked

**Comment by luite** [comment]
I think the default should now be to search for `nodejs` first and fall
back to `node` if it cannot be found.
