### ISSUE TITLE
Linking errors w/ ghc 8.0.2?

### ISSUE THREAD

**Issue by fosskers** [ghcjs/ghcjs#623]
Hi there. I've gotten tantalizingly close to having a working setup with `8.0.2`. My GHCjs compiles and boots fine, but upon building of library dependencies I see:
```
--  While building custom Setup.hs for package safe-0.3.14 using:
     /home/colin/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9009021_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs build --ghcjs-options " -ddump-hi -ddump-to-file"
   Process exited with code: ExitFailure 1
   Logs have been written to: /home/colin/code/haskell/fosskers.ca/.stack-work/logs/safe-0.3.14.log

   uncaught exception in Haskell main thread: ReferenceError: h$opendir is not defined
   ReferenceError: h$opendir is not defined
       at h$$asK (/home/colin/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9009021_ghc-8.0.2:82080:11)
       at h$runThreadSlice (/home/colin/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9009021_ghc-8.0.2:8297:11)
       at h$runThreadSliceCatch (/home/colin/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9009021_ghc-8.0.2:8251:12)
       at Immediate.h$mainLoop (/home/colin/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9009021_ghc-8.0.2:8246:9)
       at runCallback (timers.js:756:18)
       at tryOnImmediate (timers.js:717:5)
       at processImmediate [as _immediateCallback] (timers.js:697:5)
   /home/colin/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9009021_ghc-8.0.2:22854
                   h$handlErrnoC(err, -1, 0, c);
                   ^
   
   ReferenceError: h$handlErrnoC is not defined
       at /home/colin/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9009021_ghc-8.0.2:22854:17
       at FSReqWrap.oncomplete (fs.js:166:21)
```
Any idea what causes this? Thank you.

**Comment by luite** [comment]
The first exception is caused by some haskell code calling the `opendir` function from a foreign import. It looks like the `unix` package might be responsible. I'll look into this (hopefully it can actually be implemented, but in case the operation can't be supported on node.js it should produce an unsupported operation exception instead of this ReferenceError)

The second is caused by a typo in `pkg/base.js` (under shims), I'll push a fix for that soon.

**Comment by matchwood** [comment]
@fosskers I'm currently in the process of trying to put together a release of ghcjs for stack lts 9.21, which uses ghc 8.0.2 . When you say that you were close to having a working setup do you mean compiling the current ghc-8.0 branch with ghc-8.0.2? Or also updating the ghcjs-boot libraries to the 8.0.2 versions?

**Comment by fosskers** [comment]
I'm sorry I don't remember :(

**Comment by matchwood** [comment]
Haha no problem, playing with ghcjs always seems to leave blanks in my memory as well! Thanks for replying anyway.

**Comment by luite** [comment]
I fixed the exception `ReferenceError: h$handlErrnoC is not defined`, that was a typo.

Something is using `h$opendir` which is not implemented. Do you know if that's from the `Cabal` library itself, or some package's custom setup code?

**Comment by matchwood** [comment]
As established above I'm not entirely sure what @fosskers was doing when they ran into this issue, but I have put together an sdist for stack lts-9.21, based on the latest code in the ghc-8.0 branch of ghcjs https://github.com/matchwood/ghcjs-stack-dist/tree/develop and I have used it to succesfully compile a project with `safe-0.3.15` as a dependency, so I think this issue may have been resolved somehow?
