### ISSUE TITLE
ghc-8.2 branch makePackages.sh fails

### ISSUE THREAD

**Issue by sheyll** [ghcjs/ghcjs#640]
This is what I did:

     git clone https://github.com/ghcjs/ghcjs.git
     cd ghcjs
     git checkout ghc-8.2
     git submodule update --init --recursive
     ./utils/makePackages.sh

Like the README suggests.
I expected that `./utils/makePackages.sh` completes without error, but I get this output:

    populating source tree by copying upstream files
    copying package (source distribution): base
    Distribution quality errors:
    The 'build-type' is 'Configure' but there is no 'configure' script. You
    probably need to run 'autoreconf -i' to generate it.
    Note: the public hackage server would reject this package.
    Warning: Cannot run preprocessors. Run 'configure' command first.
    Building source dist for base-4.10.1.0...
    configure: fileAccess: does not exist (No such file or directory)%

**Comment by MarcFontaine** [comment]
I can reproduce the problem with makePackages.sh in 44ee1a12b98b86e82957c08bc372fe9a4b83d342

I seems to work with an older version of makePackages.sh
https://github.com/ghcjs/ghcjs/blob/30686b0d36a202ee281fbd5adb98a8f84cfec88e/utils/makePackages.sh

**Comment by hvr** [comment]
Duplicate of #634

**Comment by sheyll** [comment]
Oh sorry, somehow I didn't see that. Closing this because it is a duplicate.
