### ISSUE TITLE
ghcjs-boot having trouble

### ISSUE THREAD

**Issue by dgh1000** [ghcjs/ghcjs#643]
I followed the instructions to get ghsjs working on my MacBook. Having problems. I got as far as running 'ghcjs-boot --dev'. It's giving errors. 

First, is there a way to stop it from rebuilding everything every time I run ghcjs-boot? I just need to get it past the problem point, which is something to do with autoconf not being installed or not working. Unfortunately I shut down my computer after the last time I ran it, so I don't know the latest message. The problem is that every time I want to check if it works now, it builds for 20 minutes or so just to get back to where it left off.

M

**Comment by cdsmith** [comment]
I don't believe it's possible to incrementally boot.

As for the error, obviously no one is likely to know how to help until you provide the error message.

**Comment by dgh1000** [comment]
I wanted to find out if there's a way to check progress without waiting 20 minutes each time. As apparently there is not, I ran it again and here is the error:

Users/Mike/.ghcjs/x86_64-darwin-0.2.0-7.10.2/ghcjs/ghcjs-boot/boot/directory$ [autoreconf]: /usr/local/bin/autoreconf 
/usr/local/bin/autoreconf
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
ghcjs-boot: error running: /usr/local/bin/autoreconf
exit status: 1
stderr: Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

**Comment by cdsmith** [comment]
This may help: https://superuser.com/questions/383580/how-to-install-autoconf-automake-and-related-tools-on-mac-os-x-from-source

**Comment by cdsmith** [comment]
In particular, it seems you may need to install automake as well as autoconf (see https://github.com/Homebrew/legacy-homebrew/issues/38015)

**Comment by luite** [comment]
for debugging problems I usually I run `ghcjs-boot -v 2` so it outputs the commands, then rerun what failed manually. To disable the ghcjs internal boot library checks, set an environment variable with `export GHCJS_BOOTING=1`

**Comment by dgh1000** [comment]
Installing automake as well as autoconf fixed it! Thanks.
