### ISSUE TITLE
Emacs mode for ghcjs with flymake?

### ISSUE THREAD

**Issue by dgh1000** [ghcjs/ghcjs#645]
Is there a way to use flymake with any of the Haskell Emacs modes together with ghcjs?

**Comment by luite** [comment]
In principle it should work the same way as with `ghc`. do you see any problems?

**Comment by dgh1000** [comment]
I didn't realize it would work the same as ghc. In the meantime I decided to try purescript rather than ghcjs for my project, so this isn't an issue for me for the time being.
