### ISSUE TITLE
installation with GHC 8.4: "Haddock's resource directory does not exist"

### ISSUE THREAD

**Issue by Mikolaj** [ghcjs/ghcjs#653]
I was installing according to https://github.com/ghcjs/ghcjs/blob/ghc-8.4/README.markdown

When runnign `ghcjs-boot`, I got "fatal: program ghcjs-run is required but could not be found at ghcjs-run", so I did

    ln -s /home/mikolaj/r/ghcjs/utils/dist-newstyle-wrapper.sh ghcjs-run

and it fixed the problem. I also got "ghcjs-boot: /home/mikolaj/r/ghcjs/boot.yaml: openBinaryFile: does not exist (No such file or directory)" so instead I invoked it as

    ghcjs-boot -s data/boot.tar

and the problem vanished. After a lot of compilation it looked as it would succeed, but it failed with

    ghcjs-boot: error running: /home/mikolaj/local/bin/haddock-ghcjs --gen-contents --gen-index -o html '--title=GHCJS Libraries' --read-interface=.././lib/base-4.11.1.0/html/,./lib/base-4.11.1.0/html/base.haddock --read-interface=.././lib/ghcjs-prim-0.1.1.0/html/,./lib/ghcjs-prim-0.1.1.0/html/ghcjs-prim.haddock --read-interface=.././lib/ghc-boot-th-8.4.2.20180505/html/,./lib/ghc-boot-th-8.4.2.20180505/html/ghc-boot-th.haddock --read-interface=.././lib/text-1.2.3.0/html/,./lib/text-1.2.3.0/html/text.haddock --read-interface=.././lib/ghc-boot-8.4.2.20180505/html/,./lib/ghc-boot-8.4.2.20180505/html/ghc-boot.haddock --read-interface=.././lib/ghcjs-th-0.1.0.0/html/,./lib/ghcjs-th-0.1.0.0/html/ghcjs-th.haddock --read-interface=.././lib/directory-1.3.1.5/html/,./lib/directory-1.3.1.5/html/directory.haddock --read-interface=.././lib/bytestring-0.10.8.2/html/,./lib/bytestring-0.10.8.2/html/bytestring.haddock --read-interface=.././lib/integer-gmp-1.0.2.0/html/,./lib/integer-gmp-1.0.2.0/html/integer-gmp.haddock --read-interface=.././lib/process-1.6.3.0/html/,./lib/process-1.6.3.0/html/process.haddock --read-interface=.././lib/ghc-prim-0.5.2.0/html/,./lib/ghc-prim-0.5.2.0/html/ghc-prim.haddock --read-interface=.././lib/unix-2.7.2.2/html/,./lib/unix-2.7.2.2/html/unix.haddock --read-interface=.././lib/mtl-2.2.2/html/,./lib/mtl-2.2.2/html/mtl.haddock --read-interface=.././lib/time-1.8.0.2/html/,./lib/time-1.8.0.2/html/time.haddock --read-interface=.././lib/ghci-8.4.2.20180505/html/,./lib/ghci-8.4.2.20180505/html/ghci.haddock --read-interface=.././lib/template-haskell-2.13.0.0/html/,./lib/template-haskell-2.13.0.0/html/template-haskell.haddock --read-interface=.././lib/array-0.5.2.0/html/,./lib/array-0.5.2.0/html/array.haddock --read-interface=.././lib/parsec-3.1.13.0/html/,./lib/parsec-3.1.13.0/html/parsec.haddock --read-interface=.././lib/containers-0.5.11.0/html/,./lib/containers-0.5.11.0/html/containers.haddock --read-interface=.././lib/filepath-1.4.2/html/,./lib/filepath-1.4.2/html/filepath.haddock --read-interface=.././lib/ghc-8.4.2.20180505/html/,./lib/ghc-8.4.2.20180505/html/ghc.haddock --read-interface=.././lib/binary-0.8.5.1/html/,./lib/binary-0.8.5.1/html/binary.haddock --read-interface=.././lib/transformers-0.5.5.0/html/,./lib/transformers-0.5.5.0/html/transformers.haddock --read-interface=.././lib/deepseq-1.4.3.0/html/,./lib/deepseq-1.4.3.0/html/deepseq.haddock --read-interface=.././lib/Cabal-2.2.0.1/html/,./lib/Cabal-2.2.0.1/html/Cabal.haddock --read-interface=.././lib/pretty-1.1.3.6/html/,./lib/pretty-1.1.3.6/html/pretty.haddock
    exit status: 1
    stderr: Haddock's resource directory does not exist!

**Comment by Mikolaj** [comment]
BTW, I was using the `cabal new-build` route and it worked fine.

**Comment by ddssff** [comment]
This just happened to me with ghc-8.2.   I was going to report it this morning.

**Comment by luite** [comment]
@ddssff are you also using `cabal new-build`?

**Comment by ddssff** [comment]
Yes.  Almost exactly what the ghcjs/ghcjs readme.md file describes.  These are the differences:

1. Need to specify the branch when cloning ghcjs
2. Add ghcjs-run to list of linked executables
3. add -s data/boot.tar to ghcjs-boot command
3. added absolute paths for . and bin to $PATH

**Comment by ddssff** [comment]
I used this script to run ghcjs-boot:

    rm -rf bin
    mkdir -p bin
    ln -s ../utils/dist-newstyle-wrapper.sh bin/ghcjs
    ln -s ../utils/dist-newstyle-wrapper.sh bin/ghcjs-pkg
    ln -s ../utils/dist-newstyle-wrapper.sh bin/haddock-ghcjs
    ln -s ../utils/dist-newstyle-wrapper.sh bin/hsc2hs-ghcjs
    ln -s ../utils/dist-newstyle-wrapper.sh bin/ghcjs-boot
    ln -s ../utils/dist-newstyle-wrapper.sh bin/ghcjs-run
    export PATH=/home/dsf/git/ghcjs-debian/ghcjs:/home/dsf/git/ghcjs-debian/ghcjs/bin:$PATH
    ghcjs-boot -s data/boot.tar

I can attach the output.

**Comment by ddssff** [comment]
[out.log](https://github.com/ghcjs/ghcjs/files/1997626/out.log)

**Comment by luite** [comment]
Ok, I think that's enough to find the problem. The `new-build` wrapper is a bit of a hack, since there is no `new-install` (or maybe that has been fixed now?).

I don't use it myself that often, but of course it should be fixed, especially since it's the first of the installation options in the readme.

**Comment by ddssff** [comment]
one or the other should be fixed :-)

**Comment by luite** [comment]
I suspect part of the problem is that the data files for the `ghc-api-ghcjs` package are not installed by `cabal new-build`.

We should then be able to work around that by copying the resources in the GHCJS library directory and making sure that all the right override flags are passed to the executable.

**Comment by cocreature** [comment]
FTR, `new-install` exists since [cabal-install-2.2](https://github.com/haskell/cabal/blob/765de7b38c224df633ee88c32a9a062ecae8cc7d/cabal-install/changelog#L16) and afaik it installs data files. Given that `new-build` is still in some kind of preview state I don’t think supporting older versions is particularly important.

**Comment by luite** [comment]
ok, let's check if this still happens with `cabal-install-2.2` then

**Comment by ddssff** [comment]
I've tried copying `ghc/utils/haddock/haddock-api/resources` to a bunch of different places in `$HOME/.ghcjs//x86_64-linux-8.2.0.1-8.2.2/ghcjs` but I'm still getting the error.

**Comment by luite** [comment]
@ddssff for finding a workaround, perhaps check with `strace` to see which locations it's looking

**Comment by luite** [comment]
I've installed things with `cabal-install-2.2.0.0` and `new-build` and I'm also getting the error.

**Comment by Mikolaj** [comment]
It worked with the 'Cabal sandbox' method, though I forgot one is supposed to use the .cabal-sandbox/bin directory and instead I soft-linked to dist-newstyle-wrapper.sh. as before, ending up with `[0-9]*` in the main path :)

    writing /home/mikolaj/.ghcjs/ghcjs-[0-9]*-8.4.2.20180420/ghcjs/ghcjs_boot.completed

**Comment by ddssff** [comment]
@luite - ah, strace, what joy...  :upside_down_face:

**Comment by ddssff** [comment]
These commands make the messages go away:





	rsync -aHxS --delete ghc/utils/haddock/haddock-api/ $HOME/.ghcjs/x86_64-linux-8.2.0.1-8.2.2/ghcjs/haddock-api
	PATH=$PWD/bin:$PATH haddock_api_ghcjs_datadir=../../../../ghcjs/haddock-api/resources ghcjs-boot -s data/boot.tar

**Comment by ddssff** [comment]
Now I get to this.  Strange.

    patching file filepath.cabal
    The next patch would create the file System/FilePath/Current.hs,
    which already exists!  Assume -R? [n]

(I have a possible fix)

**Comment by luite** [comment]
workaround: `rm -r ./lib/boot/pkg` first. maybe the script should do that automatically.

but I still need to find something better than the current patching method.

**Comment by luite** [comment]
I've added this to the `utils/makePackages.sh` script now. I'm not terribly happy with removing the files this way, but it's probably better than people stuck on this error.

**Comment by ddssff** [comment]
I did this:

    rm -rf "$PKGDST"; mkdir -p "$PKGDST"; cd "$PKGDST"
    echo "unpacking sources: $SRCDIST"
    tar --strip 1 -xzf "$SRCDIST"

**Comment by Mikolaj** [comment]
Closing in favour of #5840. Please open specific issue if any anything else is not resolved (most problems from my original post are fixed in PR #726).
