### ISSUE TITLE
8.4: Pattern match checker exceeded (2000000) iterations building Gen2.Prim

### ISSUE THREAD

**Issue by ElvishJerricco** [ghcjs/ghcjs#655]
When building GHCJS 8.4 with this PR https://github.com/NixOS/nixpkgs/pull/40392, I get this error:

```
src/Gen2/Prim.hs:77:1: warning:
    Pattern match checker exceeded (2000000) iterations in
    an equation for ‘genPrim’. (Use -fmax-pmcheck-iterations=n
    to set the maximun number of iterations to n)
   |
77 | genPrim _ _ CharGtOp          [r] [x,y] = PrimInline [j| `r` = (`x` > `y`) ? 1 : 0; |]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

To reproduce, checkout that PR and run `nix-build -A haskell.compiler.ghcjs84`

Entire build log: https://gist.github.com/ElvishJerricco/b724ec9ff9f9380a066ff0495f2e65f1

**Comment by luite** [comment]
That's a warning not an error. The code is not yet earning-free. I will go
through the code later to fix more warnings, but I am not sure if this one
can be fixed in a meaningful way, due to the way genPrim works.

**Comment by ElvishJerricco** [comment]
@luite Oh, perhaps I posted the wrong part of the build log. It certainly exited as a failure

**Comment by ElvishJerricco** [comment]
Ah: https://gist.github.com/ElvishJerricco/b724ec9ff9f9380a066ff0495f2e65f1#file-gistfile1-txt-L761

So this is probably a package version issue in nixpkgs. Will close this once I confirm that

**Comment by ElvishJerricco** [comment]
Looks like it's difficult/impossible to build the dependencies correctly with GHC 8.4 without breaking the build this way. Either we can do the build with 8.2 instead (is it ok to build GHCJS 8.4 with GHC 8.2?), or we can simply remove the [use of `Text.PrettyPrint.Leijen.Text.(<>)`](https://github.com/ghcjs/ghcjs/blob/3959a9321a2d3e2ad4b8d4c9cc436fcfece99237/src/Gen2/Printer.hs#L17)
