### ISSUE TITLE
Minor: all.js.externs doesn't seem to do anything

### ISSUE THREAD

**Issue by Mikolaj** [ghcjs/ghcjs#661]
The main difference when using `all.js.externs` is the size of the resulting optimized javascript. Regardless of the externs file, testing using `node`, instead of in the browser, fails, though the failure messages do differ. Without `ccjs` the `node` testing runs fine and it always runs fine in the browser.

ccjs dist/build/LambdaHack/LambdaHack.jsexe/all.js --compilation_level=ADVANCED_OPTIMIZATIONS --isolation_mode=IIFE --assume_function_wrapper --jscomp_off="*" --externs=dist/build/LambdaHack/LambdaHack.jsexe/all.js.externs 

Size 6156357. Message "ReferenceError: window is not defined".

ccjs dist/build/LambdaHack/LambdaHack.jsexe/all.js --compilation_level=ADVANCED_OPTIMIZATIONS --isolation_mode=IIFE --assume_function_wrapper --jscomp_off="*" --externs=node

Size 6116727. Message: something to the effect that `stdout` is not `hIsTerminalDevice` (that is coming from a test in LambdaHack codebase, originally added to prevent failures when running natively under Windows).

ccjs dist/build/LambdaHack/LambdaHack.jsexe/all.js --compilation_level=ADVANCED_OPTIMIZATIONS --isolation_mode=IIFE --assume_function_wrapper --jscomp_off="*"

Size 6116640. Message "ReferenceError: window is not defined".

```
~/r/LambdaHack$ ccjs --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20171203
Built on: 2017-12-05 14:07
```

**Comment by luite** [comment]
The externs file protects some properties that the rts may access with a string lookup (`x.d100` and `x["d100"]`). Clearly something else is still broken here.

**Comment by Mikolaj** [comment]
Thank you for the explanation. In that case, I will start using these externs, just in case.

I tried both externs at once, ghcjs' and node's, but the problem persists, namely, this condition

https://github.com/LambdaHack/LambdaHack/blob/aaeaf3f1eff5e76a64f14263fa7f1e17abfad2c1/GameDefinition/Main.hs#L29

is true before ccjs minification, but is false afterwards. I worked around, by disabling the test when compiled by ghcjs and now I can benchmark the minified code under node, at last. BTW, it turns out the code "optimized" by ccjs is actually slower than the original code. :) However, it's much smaller indeed, down to 6M (16FPS) from 22M (17FPS) with --dedupe and 41M (15FPS) without --dedupe.

**Comment by Mikolaj** [comment]
Now, with 8.6 branch, the story is different. Both before minification and after (with the same ccjs version as in the bug report, I think), it fails on the browser (previously it never did). Which probably means that now `hIsTerminalDevice stdout` is false, while it was true before. Probably OK.

With node, again results are the same before and after and it runs fine (which means `hIsTerminalDevice stdout` is true). Previously after minification there was failiure, 

So either the externs give now more safety or something else has changed (`hIsTerminalDevice`?). Closing.

**Comment by Mikolaj** [comment]
Reopening, because I was testing wrong files and came to wrong conclusions: sadly, with node after minification 'hIsTerminalDevice stdout' is false, while before minification it's true. So it's the same problem as in the original report, even though the behaviour in the browser has changed. I get the same results with old ccjs (from May) and a new one (current).

**Comment by Mikolaj** [comment]
Finally, it has the same behaviour in all scenarios. Closing for good. Thank you!
