### ISSUE TITLE
Serialize instance for Double does not match ghc's, possible endian problem

### ISSUE THREAD

**Issue by cliffordbeshers** [ghcjs/ghcjs#670]
We are seeing different encodings of a Double in ghc versus ghcjs using
 Data.Serialize. The attached program runs differently, apparently due to the implementation of    put = putFloat64be and/or getFloat64be, used in the Serialize instance for Double.

[DoubleSerializeGHCJS.txt](https://github.com/ghcjs/ghcjs/files/2130077/DoubleSerializeGHCJS.txt)

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
$ ghcjs --version
The Glorious Glasgow Haskell Compilation System for JavaScript, version 0.2.1 (GHC 8.0.2)

**Comment by ddssff** [comment]
Here is a ghcjs test program that demonstrates this issue:

    {-# LANGUAGE OverloadedStrings, ScopedTypeVariables #-}

    import Data.ByteString
    import Data.Serialize
    import System.Process
    import Test.QuickCheck
    import System.IO.Unsafe
    import Data.Typeable (Proxy(Proxy), typeRep, Typeable)

    main :: IO ()
    main = do
      quickCheck (prop_ghc_encode_ghcjs_decode :: Double -> Bool)
      quickCheck (prop_ghcjs_encode_ghc_decode :: Double -> Bool)

    prop_ghc_encode_ghcjs_decode :: (Arbitrary a, Eq a, Serialize a, Show a) => a-> Bool
    prop_ghc_encode_ghcjs_decode x = decode (ghcEncode x) == Right x

    prop_ghcjs_encode_ghc_decode :: (Arbitrary a, Eq a, Serialize a, Read a, Typeable a) => a -> Bool
    prop_ghcjs_encode_ghc_decode x = ghcDecode (encode x) == Right x

    ghcEncode :: forall a. (Show a, Serialize a) => a -> ByteString
    ghcEncode x = unsafePerformIO $ (read <$> readProcess "ghc" ["-e", "Data.Serialize.encode (" ++ show x ++ ")"] mempty)

    ghcDecode :: forall a. (Read a, Serialize a, Typeable a) => ByteString -> Either String a
    ghcDecode bytes = unsafePerformIO $
      read <$> readProcess "ghc" ["-XOverloadedStrings", "-e",
                                  "Data.Serialize.decode (" ++ show bytes ++
                                  ") :: Either String (" ++ show (typeRep (Proxy :: Proxy a)) ++ ")"] mempty

**Comment by ddssff** [comment]
Clearly this reflects the differences in the representation of the various types.  So not a ghcjs bug, but something to keep in mind.

**Comment by ddssff** [comment]
Improved version of test program demonstrates that only Double is affected:
https://lpaste.net/2158466377592078336

**Comment by luite** [comment]
I'm not seeing any errors running the test program on 8.4

I think this was fixed in 8.2.

(8.2 and up assume that the underlying system is little endian. unfortunately some endianness things are still baked in by the compiler/preprocessor, and in JS we can't be completely sure what we get until runtime. on little endian systems the results should be consistent with GHC though)

**Comment by luite** [comment]
I think this was fixed. Please open a new ticket if it still happens with the `ghc-8.4` or `ghc-8.6` branch
