### ISSUE TITLE
resizeMutableByteArray primop

### ISSUE THREAD

**Issue by andrewthad** [ghcjs/ghcjs#686]
Does `resizeMutableByteArray` work correctly with GHCJS? I'm getting this error:

```
warning, unhandled primop: ResizeMutableByteArrayOp_Char (1,2)
uncaught exception in Haskell thread: ReferenceError: h$primop_ResizeMutableByteArrayOp_Char is not defined
```

**Comment by andrewthad** [comment]
I'm going to try this out in our development environment. I'm mostly concerned about the implementation for `shrinkMutableByteArray#`. I think I've got the right way to do it in-place.

**Comment by andrewthad** [comment]
Sorry, that comment was supposed to go on the PR.

**Comment by luite** [comment]
thanks, merged.

the in-place way for `shrinkMutableByteArray#` looked like the right way to do it.
