### ISSUE TITLE
Incorrect primops for writing Int8 and Int16 bytearrays

### ISSUE THREAD

**Issue by andrewthad** [ghcjs/ghcjs#689]
The [code for writing `Int8` and `Int16` to a bytearray](https://github.com/ghcjs/ghcjs/blob/3959a9321a2d3e2ad4b8d4c9cc436fcfece99237/src/Gen2/Prim.hs#L339-L340) is currently:

```
genPrim _ _ WriteByteArrayOp_Int8 [] [a,i,e] = PrimInline [j| `a`.dv.setInt8(`i`, `e`, false); |]
genPrim _ _ WriteByteArrayOp_Int16 [] [a,i,e]     = PrimInline [j| `a`.dv.setInt16(`i`<<1, `e`, false); |]
```

The [code for reading `Int8` and `Int16` from a bytearray](https://github.com/ghcjs/ghcjs/blob/3959a9321a2d3e2ad4b8d4c9cc436fcfece99237/src/Gen2/Prim.hs#L315-L316) is:

```
genPrim _ _ ReadByteArrayOp_Int8 [r] [a,i] = PrimInline [j| `r` = `a`.dv.getInt8(`i`,true); |]
genPrim _ _ ReadByteArrayOp_Int16 [r] [a,i] = PrimInline [j| `r` = `a`.dv.getInt16(`i`<<1,true); |]
```

Notice that the boolean arguments differ. These control endianness. The ones for `WriteByteArrayOp_Int8` and `WriteByteArrayOp_Int16` should be `true`, not `false`.

**Comment by andrewthad** [comment]
I have fixed this as a part of https://github.com/ghcjs/ghcjs/pull/687. I've tested this change locally against my `primitive-containers` library, and it has the desired effect.

**Comment by luite** [comment]
good, thanks, merged!
