### ISSUE TITLE
makeStableName fails on Bool?

### ISSUE THREAD

**Issue by cdsmith** [ghcjs/ghcjs#700]
It seems that makeStableName in GHCJS throws an exception when called on a `Bool`.  See https://github.com/google/codeworld/issues/747 for reproduction using CodeWorld.  I have not tried to reproduce outside of CodeWorld, but I am not doing anything that should change the behavior here.

**Comment by cdsmith** [comment]
Looks like the relevant code is https://github.com/ghcjs/shims/blob/master/src/mem.js#L981

I'm going to guess that `Bool` values are stored immediately as booleans in JavaScript, and this function is just missing a case for JavaScript booleans?

**Comment by cdsmith** [comment]
Okay, here's a simpler test case.  Using CodeWorld, but not using any of the CodeWorld library.  Presumably you could do the same from the GHCJS 8.0 branch via the CLI.

https://code.world/haskell#P636l8TAIFd4uz8OTVDpLzA

**Comment by cdsmith** [comment]
By reading the source code, this looks like still a bug in 8.4.  https://github.com/ghcjs/ghcjs/blob/ghc-8.4/lib/boot/shims/src/mem.js#L1097

(I haven't tested this, though.)

**Comment by cdsmith** [comment]
@luite  This looks like something that might have an easy fix.  If so, could you spare a minute to point me in the right direction?  Even if the fix doesn't get released in GHCJS soon, I'd love to patch locally on the CodeWorld server.  Not being able to use `Bool` as a state type in CodeWorld is interfering with a lesson sequence I'm working on.

**Comment by luite** [comment]
ah yes, it shouldn't throw an exception.

StableNames are represented either as a number of as an object. For `Bool` we need another case. There are just two `Bool` constructors, so two special top level StableName objects for those looks like the most obvious choice.

I'll implement and test that.

**Comment by luite** [comment]
Added a fix.

There is a quirk in the `StableName` behaviour though: If runtime representations are identical, the returned stable names may be equal, even if the object is a different type.

A `Word` and an `Int` or `Double` mapping to the same JavaScript number will get the same `StableName`. I'm not sure if that represents a problem in practice.

**Comment by cdsmith** [comment]
Thanks!

That cross-type case doesn't matter for me, since I don't compare stable names across types.  I'm not sure if it would matter for anyone else.

**Comment by luite** [comment]
This change doesn't make the cross-type behaviour any worse.

I think I can close this.
