### ISSUE TITLE
New regex failure bug with latest ghcjs-8.4 patches

### ISSUE THREAD

**Issue by ddssff** [ghcjs/ghcjs#709]
This program, similar to the one used in bug #649, starts failing with the latest patches:
```
{-# LANGUAGE PackageImports #-}

import "regex-compat-tdfa" Text.Regex

main :: IO ()
main = do
  putStrLn $ show $
    matchRegex (mkRegex "^([ \t]*\\$[ \t]*)?([0-9,]*\\.[0-9][0-9]|[0-9,]+)") "$700,000"
```
Using the regex package that does not use the FFI:
```
$ ghcjs Foo.hs -o foo && nodejs ./foo.jsexe/all.js
[1 of 1] Compiling Main             ( Foo.hs, Foo.js_o )
Linking foo.jsexe (Main)
uncaught exception in Haskell main thread: ReferenceError: h$$regexzmtdfazm1zi2zi3zi1zmJXSLhpaP2WiIMuPRuAT0BtZCTextziRegexziTDFAziNewDFAziEnginezilvl306_1_vSfXWjYEuZ0 is not defined
ReferenceError: h$$regexzmtdfazm1zi2zi3zi1zmJXSLhpaP2WiIMuPRuAT0BtZCTextziRegexziTDFAziNewDFAziEnginezilvl306_1_vSfXWjYEuZ0 is not defined
    at h$$dAj (/home/dsf/git/autobuilder-seereason/foo.jsexe/all.js:321491:5)
    at h$runThreadSlice (/home/dsf/git/autobuilder-seereason/foo.jsexe/all.js:8702:11)
    at h$runThreadSliceCatch (/home/dsf/git/autobuilder-seereason/foo.jsexe/all.js:8658:12)
    at Immediate.h$mainLoop [as _callback] (/home/dsf/git/autobuilder-seereason/foo.jsexe/all.js:8653:9)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```
Using stock ghcjs-8.4:
```
$ ghcjs Foo.hs -o foo && nodejs ./foo.jsexe/all.js
[1 of 1] Compiling Main             ( Foo.hs, Foo.js_o )
Linking foo.jsexe (Main)
Just ["$","700,000"]
```

**Comment by ddssff** [comment]
Not the absolute latest patches, the ghcjs compiler was built from head on November 2nd.

**Comment by luite** [comment]
I think I have already run into this with a different package. Something
wrong with string literal references I think.

**Comment by ddssff** [comment]
Would it be worth narrowing it down to the particular patch where it started?  Because it doesn't happen with stock 8.4.0.1.

**Comment by luite** [comment]
I corrected the problem I was seeing in d1ded1f890e7ebebbbb462bb5a321983bb6be914

I think that will also correct this.

**Comment by ddssff** [comment]
Regex failure is gone, application now starts but dies with this (which I haven't tried to track down, but maybe it rings a bell)

    uncaught exception in Haskell main thread: TypeError: Cannot read property 't' of undefined
    rts.js:7507 TypeError: Cannot read property 't' of undefined
      at h$e (rts.js:19589)
      at h$$u0u (out.js:1018608)
      at h$runThreadSlice (rts.js:8620)
      at h$runThreadSliceCatch (rts.js:8577)
      at h$mainLoop (rts.js:8572)
      at rts.js:2521
      at runIfPresent (rts.js:2539)
      at onGlobalMessage (rts.js:2580)

**Comment by luite** [comment]
hmm, nope. could be many of the recent changes. maybe the thunk update thing.

I'll run more extensive tests first, perhaps I find a small program that reproduces this.

**Comment by luite** [comment]
hmm, I'm not seeing unexpected things with the `testPackages.sh` script, but the regular testsuite has  more failures that are worth looking into.

**Comment by luite** [comment]
are you using incremental linking by the way?

**Comment by cliffordbeshers** [comment]
Nope, no incremental linking.

**Comment by luite** [comment]
hmm, most testsuite failures I'm seeing actually appear to be related to that, work fine when linked in one go.

**Comment by cliffordbeshers** [comment]
When we were switching from 7.10 to 8.x, we saw a failure at startup that
was slightly different.  I think I saw it recently in another thread, d1
field 1 undefined or something.  There was an unsafecoerce in a library I
had cloned. Removing that solved the problem.  We haven't seen this kind of
failure since.  Not sure how that might help.

**Comment by luite** [comment]
Ah those bugs can be tricky to track down.

Earlier this year I made some debugging tools that inspect heap objects and
primitive values at runtime, but I don't remember how much is already in
the code.

Maybe I will push more complete tools later. Otherwise I might ask to have
a look at the compiled program.

In the meantime you can add the `-debug` flag when linking. That will
preserve the z-encoded package and module names for non-exported symbols.
Perhaps that will point you in the right direction.

**Comment by ddssff** [comment]
I will try -debug

**Comment by ddssff** [comment]
Oh, this might be a problem with my build procedure.

**Comment by ddssff** [comment]
Great news, its all running fine now - sorry about the mix up.

**Comment by cdsmith** [comment]
@ddssff Do you know what your build procedure was doing to cause this?  If so, it would be great to have the cause and how to fix it recorded in this issue in case someone else ends up here for the same reason.

**Comment by ddssff** [comment]
I suspect I bounced back to the old compiler for the final steps of the compile.  Mixing up the test and "production" environments.
