### ISSUE TITLE
Support new "Performance" panel in Chrome devtools

### ISSUE THREAD

**Issue by luite** [ghcjs/ghcjs#712]
Profiling with the Electron devtools only work with the old "Javascript Profiler" found under "more tools"

The new "Performance" panel gets the profile incrementally with different messages.

I think it's possible to support this as well, but perhaps the way cost centres are updated needs to be improved.

**Comment by luite** [comment]
Looks like the cost centre stacks are upside down in the current version.

I think I made some mistake when changing how the devtools retrieve the cost centre stacks

(In an earlier version, the Haskell runtime reported each cost centre with a special message, but the devtools would miss cost centres reported before they fully started. Now the devtools just retrieve the cost centres by executing some JS code on the target before processing the profiling data)

**Comment by luite** [comment]
I don't have the performance pane working yet, but I got a little further.

Cost centres can be retrieved incrementally with a small change in the code sent to the program (slicing the array first).

The messages have to be delivered in order (or at least the ones with data before the "end of profiling" message), so delaying only the ones with cost centres to retrieve the cost centre information does cause problems. Relatively easy to fix by queueing the messages.

Rewriting the call frames correctly may be a little more work.

**Comment by luite** [comment]
I think it's probably easiest to recursively call some JS functions to "stuff" the stack.

The cost centre stack can then be unrolled on top of these frames. If the cost centre stack is longer, the last components can be squeezed into a single frame.

It's fairly easy to make the limit configurable (I got this already working), and the frame rewriting code becomes much simpler (not complete yet).

I'm a bit on the fence if having a ccs depth limit is an acceptable tradeoff for the simplicity.

**Comment by luite** [comment]
I think the limit is probably acceptable in practice. Some improvements still needed for updating the cost centres, but the performance pane works now. You can scroll through the timeline, select, drill down the call stack. The Haskell cost centres start with a backslash.

<img width="1161" alt="performance" src="https://user-images.githubusercontent.com/354096/49079751-6f2eba80-f27c-11e8-9541-db103a08d0f4.png">

**Comment by luite** [comment]
(I haven't pushed the code yet, one or two days)

**Comment by ryantrinkle** [comment]
Awesome!

**Comment by luite** [comment]
Code now in the `ghc-8.4` branch.

The devtools protocol and message format are not really stable, so I suspect the message processing code will require changes at some point. Most likely `processProfilingNodes` and `processTracingDataMessage` in `electron-devtools-inject.js`.

The new version is much simpler, and I left many `trace` statements in place to help figure out when something goes wrong. Having a CCS stack limit is a downside, but it's an acceptable tradeoff. The value is configurable anyway, see the README.

The call frame message format has changed between the old "JavaScript Profiler" and the new "Performance" tab. Call frames used to have a `children` field, now they have a `parent`. I have updated the CCS expanding code to work with the new format.

If anyone still needs the old "JavaScript Profiler", please let me know.
