### ISSUE TITLE
MIN_VERSION_base macro forces failure when compiling individual files

### ISSUE THREAD

**Issue by agocorona** [ghcjs/ghcjs#714]
I have no problems doing `cabal install --ghcjs`   with source code which uses this macro, but fails when
I invoke ghcjs directly with a file with such macro:

```haskell
>ghcjs  myfilewithmacro.hs : 

src/Transient/Move/Internals.hs:124:0: error:
     error: missing binary operator before token "("
     #if MIN_VERSION_base(4,11,0)

    |
124 | #if MIN_VERSION_base(4,11,0)
    | ^

```

**Comment by luite** [comment]
Hmm I vaguely recall GHC changing it's behaviour. Does it work with GHC now?

**Comment by agocorona** [comment]
Yes, ghc 8.2 works well in both cases for me...

**Comment by cdsmith** [comment]
Just to check the obvious things: this will need the CPP language extension.  Have you listed the extension in your cabal file, rather than in a LANGUAGE pragma?  If so, you would need to pass -XCPP when compiling with ghc or ghcjs directly.

**Comment by agocorona** [comment]
adding -XCPP the error is the same.  the CPP option is in the source code 

`{-# LANGUAGE CPP                       #-}`

it seems that for some reason the preprocessor does not recognize the macro, while the one used by Cabal does it. I made a trace of the cabal execution and it does nothing strange. Perhaps I'm horribly wrong

**Comment by luite** [comment]
older versions of GHC relied on Cabal to provide these macros. GHC does it itself now.

I must have done something wrong when updating.

**Comment by luite** [comment]
I think I missed an update from the DriverPipeline module

**Comment by luite** [comment]
I've added support for it

**Comment by agocorona** [comment]
great! is that version available?

**Comment by luite** [comment]
It's in the ghc-8.4 branch.

**Comment by agocorona** [comment]
Could it be added to the 8.2 branch too?

**Comment by luite** [comment]
there are quite a few issues not backported to 8.2. do you need to use 8.2?

if people only use 8.2 for testing packages with various compiler versions, I'm not sure if it's worth the trouble of backporting these things. Especially since I'm working on 8.6 support now.

**Comment by agocorona** [comment]
Ok, never mind, It is not necessary since it seems that 8.4 docker image
build well now.


Close this issue if you wish
