### ISSUE TITLE
ghcjs-8.4 fails to build heaps package

### ISSUE THREAD

**Issue by harendra-kumar** [ghcjs/ghcjs#727]
I am trying to build the "streamly" (https://github.com/composewell/streamly) package using gchjs. It builds successfully using ghcjs-8.6 version that I built myself from the ghcjs repo. However, I am trying to use hvr-ghcjs 8.4 (from the ppa hvr/ghcjs) version to build it on travis CI and it fails while building the heaps package. The logs are available here: https://travis-ci.org/composewell/streamly/jobs/478611796 .  The error looks like this:

```
Failed to build heaps-0.3.6. The failure occurred during the configure step.
Build log (
/home/travis/.cabal/logs/ghcjs-8.4.0.1/heaps-0.3.6-618683f0d3d2175fcc378d7848ff012451b5c42377f742923af77a05e13fd75f.log
):
[1 of 1] Compiling Main             ( /home/travis/build/composewell/streamly/dist-newstyle/tmp/src-9329/heaps-0.3.6/dist/setup/setup.hs, /home/travis/build/composewell/streamly/dist-newstyle/tmp/src-9329/heaps-0.3.6/dist/setup/Main.js_o )
Linking /home/travis/build/composewell/streamly/dist-newstyle/tmp/src-9329/heaps-0.3.6/dist/setup/setup.jsexe (Main)
JavaScript exception: TypeError: Object function Buffer(subject, encoding, offset) {
  if (!(this instanceof Buffer)) {
    return new Buffer(subject, encoding, offset);
  }
  var type;
  // Are we slicing?
  if (typeof offset === 'number') {
    if (!Buffer.isBuffer(subject)) {
      throw new TypeError('First argument must be a Buffer when slicing');
    }
    this.length = +encoding > 0 ? Math.ceil(encoding) : 0;
    this.parent = subject.parent ? subject.parent : subject;
    this.offset = offset;
  } else {
    // Find the length
    switch (type = typeof subject) {
      case 'number':
        this.length = +subject > 0 ? Math.ceil(subject) : 0;
        break;
      case 'string':
        this.length = Buffer.byteLength(subject, encoding);
        break;
      case 'object': // Assume object is array-ish
        this.length = +subject.length > 0 ? Math.ceil(subject.length) : 0;
        break;
      default:
        throw new TypeError('First argument needs to be a number, ' +
                            'array or string.');
    }
    if (this.length > Buffer.poolSize) {
      // Big buffer, just alloc one.
      this.parent = new SlowBuffer(this.length);
      this.offset = 0;
    } else if (this.length > 0) {
      // Small buffer.
      if (!pool || pool.length - pool.used < this.length) allocPool();
      this.parent = pool;
      this.offset = pool.used;
      // Align on 8 byte boundary to avoid alignment issues on ARM.
      pool.used = (pool.used + this.length + 7) & ~7;
    } else {
      // Zero-length buffer
      this.parent = zeroBuffer;
      this.offset = 0;
    }
    // optimize by branching logic for new allocations
    if (typeof subject !== 'number') {
      if (type === 'string') {
        // We are a string
        this.length = this.write(subject, 0, encoding);
      // if subject is buffer then use built-in copy method
      } else if (Buffer.isBuffer(subject)) {
        if (subject.parent)
          subject.parent.copy(this.parent,
                              this.offset,
                              subject.offset,
                              this.length + subject.offset);
        else
          subject.copy(this.parent, this.offset, 0, this.length);
      } else if (isArrayIsh(subject)) {
        for (var i = 0; i < this.length; i++)
          this.parent[i + this.offset] = subject[i];
      }
    }
  }
  SlowBuffer.makeFastBuffer(this.parent, this, this.offset, this.length);
} has no method 'alloc'
T
```

Any Idea what this could be? Is that a bug in ghcjs 8.4 or something else?

**Comment by harendra-kumar** [comment]
It seems none of the programs built with this compiler (hvr/ghcjs) can be run on travis - see this simple "hello world" test (https://travis-ci.org/composewell/packcheck/jobs/478610259) which shows the same issue. We are seeing this issue while building "heaps" in the original issue posted above because "heaps" has to run the setup executable. Could it be some nodejs version issue?

**Comment by hvr** [comment]
@harendra-kumar if you look at https://launchpad.net/~hvr/+archive/ubuntu/ghcjs there's some remarks about the Nodejs version bundled with various Ubuntu versions. Have you ensured to heed those warnings? Also note that you might want to use `cabal-install-head` as some of the ghcjs related improvements recently merged to `master` aren't yet in a 2.4.x release.

PS: you can steal some ideas from https://github.com/nomeata/ghcjs2gh-pages/blob/master/.travis.yml for making available a more recent nodejs version to the Travis environment.

**Comment by harendra-kumar** [comment]
@hvr I have to admit that I did not even read those remarks. Maybe if they are in bold red there will be a better chance of forcing those down someone's throat :-) But I checked the node version as displayed in the travis build information and it says:

```
Pre-installed Node.js versions
v4.8.6
v6.12.0
v6.12.1
v8.9
v8.9.1
```

Not sure which one is used by default, but all those should work as per your notes. I will try to explicitly use a particular node version. I will try the `xenial` build as well. Does your ghc ppa (hvr/ghc) work with xenial?

**Comment by harendra-kumar** [comment]
I printed the version of node that is used by gchjs on the travis CI:

```
Using ghcjs at /opt/ghcjs/8.4//bin/ghcjs
The Glorious Glasgow Haskell Compilation System for JavaScript, version 8.4.0.1 (GHC 8.4.2.20180420) [?]
[1 of 1] Compiling Main             ( /tmp/tmp.tF7c6uVAiS/test.hs, /tmp/tmp.tF7c6uVAiS/test.js_o )
Linking /tmp/tmp.tF7c6uVAiS/run.jsexe (Main)
/opt/ghcjs/8.4//bin/ghcjs uses node at [/usr/bin/nodejs]
node version [v4.2.6]
```

This is a xenial build and travis build info prints this on this machine:

```
Pre-installed Node.js versions
v10.15.0
v11.0.0
v4.9.1
v6.16.0
v8.12.0
v8.15.0
v8.9
```

And /usr/bin/nodejs is not any of these versions.

**Comment by harendra-kumar** [comment]
I installed node version to 11 and everything works fine. @hvr we can list node version 4.2.6 or 4.* as known to NOT work with ghcjs-8.4. We can also list node 11 as known to work.

**Comment by hvr** [comment]
@harendra-kumar interesting, thanks for investigating; fwiw, as an additional data-point I currently use (locally) nodejs 8.15 on Ubuntu Xenial w/ ghcjs 8.4; and according to the ghcjs 8.4 bootstrapping tool

```hs
           | otherwise -> failWith ("minimum required version for node.js is 6.0.0, found: " <> verTxt)
```

Nodejs v6.x is expected to work as well for ghcjs 8.4

But I guess it also depends on what you're trying to do; if you don't *need* to run much via nodejs (i.e. if you don't need to run testsuites and don't have custom Setup.hs etc) you can probably get away with nodejs 4.x

> Maybe if they are in bold red

unfortunately launchpad doesn't support any markup;  `text/plain` is all I got there 

In any case, I've updated the description to include your information!

**Comment by harendra-kumar** [comment]
Setup.hs and testsuites are still a pretty big usecase for node. Package maintainers would definitely want to run testcases if they have to claim ghcjs support. And Setup.hs definitely needs to be executed to build many packages on hackage and we cannot avoid it.

On local machines people generally tend have more modern versions, I have not upgraded it since many years and I have node 7.9 on my local machine and that works fine with ghcjs. But CI machines like travis seem to be too far behind. Hoping that older versions of node would be uncommon, I am not sure if it is worth the effort to detect the node version in the wrapper generated by `-build-runner` and give out a better error message saying this version is not supported. In `-build-runner` case we know that the interpreter is `node` so it should be simple.

**Comment by harendra-kumar** [comment]
For the record, my CI script (https://github.com/composewell/packcheck) detects the node version and also tries to compile a simple `hello world` program with `ghcjs` before declaring it fit to compile the project:

```
Using ghcjs at /opt/ghcjs/8.4//bin/ghcjs
The Glorious Glasgow Haskell Compilation System for JavaScript, version 8.4.0.1 (GHC 8.4.2.20180420) [?]
[1 of 1] Compiling Main             ( /tmp/tmp.tJAICngSok/test.hs, /tmp/tmp.tJAICngSok/test.js_o )
Linking /tmp/tmp.tJAICngSok/run.jsexe (Main)
/opt/ghcjs/8.4//bin/ghcjs uses node at [/usr/bin/nodejs] for executing js output
/usr/bin/nodejs is version [v11.6.0]
Trying to run a test executable produced by [/opt/ghcjs/8.4//bin/ghcjs]...
[/opt/ghcjs/8.4//bin/ghcjs] produces executables runnable by [/usr/bin/nodejs]
```

It can be used to quickly setup ghcjs CI via `hvr-ghcjs` and `cabal`.
