### ISSUE TITLE
ghcjs-boot fails with: unrecognized 'install' option `--haddock-html'

### ISSUE THREAD

**Issue by hansroland** [ghcjs/ghcjs#744]
I donwloaded ghcjs branch `ghc-8.6` according the instructions of the README.

Unfortunately the step: `ghcjs-boot -s ./lib/boot` failed with: 

> ...
> /home/roland/Software/ghcjs-8.6/lib/boot/pkg/ghc-prim$ rm_rf dist
> /home/roland/Software/ghcjs-8.6/lib/boot$ [cabal]: /home/roland/Software/ghc/bin/cabal "--config-file" "/home/roland/.ghcjs/x86_64-linux-8.6.0.1-8.6.2/ghcjs/cabalBootConfig" "--ignore-sandbox" "install" "./pkg/ghc-prim" "--allow-boot-library-installs" "--global" "--ghcjs" "--one-shot" "--avoid-reinstalls" "--builddir" "dist" "--with-compiler" "/home/roland/Software/ghcjs-8.6/.bin/ghcjs" "--with-hc-pkg" "/home/roland/Software/ghcjs-8.6/.bin/ghcjs-pkg" "--prefix" "/home/roland/.ghcjs/x86_64-linux-8.6.0.1-8.6.2/ghcjs" "--enable-documentation" "--haddock-html" "--haddock-hoogle" "--haddock-hyperlink-source" "--enable-debug-info" "--disable-library-stripping" "--disable-executable-stripping" "-fghci" "--enable-profiling" "--enable-shared" "-v2" "--dry-run"
> /home/roland/Software/ghc/bin/cabal --config-file /home/roland/.ghcjs/x86_64-linux-8.6.0.1-8.6.2/ghcjs/cabalBootConfig --ignore-sandbox install ./pkg/ghc-prim --allow-boot-library-installs --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /home/roland/Software/ghcjs-8.6/.bin/ghcjs --with-hc-pkg /home/roland/Software/ghcjs-8.6/.bin/ghcjs-pkg --prefix /home/roland/.ghcjs/x86_64-linux-8.6.0.1-8.6.2/ghcjs --enable-documentation --haddock-html --haddock-hoogle --haddock-hyperlink-source --enable-debug-info --disable-library-stripping --disable-executable-stripping -fghci --enable-profiling --enable-shared -v2 --dry-run
> cabal: unrecognized 'install' option `--haddock-html'
> 
> unrecognized 'install' option `--haddock-hoogle'
> 
> unrecognized 'install' option `--haddock-hyperlink-source'
> ghcjs-boot: error running: /home/roland/Software/ghc/bin/cabal --config-file /home/roland/.ghcjs/x86_64-linux-8.6.0.1-8.6.2/ghcjs/cabalBootConfig --ignore-sandbox install ./pkg/ghc-prim --allow-boot-library-installs --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /home/roland/Software/ghcjs-8.6/.bin/ghcjs --with-hc-pkg /home/roland/Software/ghcjs-8.6/.bin/ghcjs-pkg --prefix /home/roland/.ghcjs/x86_64-linux-8.6.0.1-8.6.2/ghcjs --enable-documentation --haddock-html --haddock-hoogle --haddock-hyperlink-source --enable-debug-info --disable-library-stripping --disable-executable-stripping -fghci --enable-profiling --enable-shared -v2 --dry-run
> exit status: 1
> stderr: cabal: unrecognized 'install' option `--haddock-html'
> 
> unrecognized 'install' option `--haddock-hoogle'
> 
> unrecognized 'install' option `--haddock-hyperlink-source'
> 

Any idea, what's wrong? Are there any flags to bypass creating documentation? Why does it try to do a `--dry-run`?

Many thanks!

**Comment by Mikolaj** [comment]
From what I understand the 8.6 branch is most supported ATM. Perhaps try comparing the two branches and see if anything related crops up? Then perhaps cherry pick some commits from 8.6 to 8.2 and let us know if it works?

**Comment by hansroland** [comment]
Uuhh sorry! There was a typo: It should read "i downloaded the **8.6** branch. I edited the failure report accordingly!

**Comment by Mikolaj** [comment]
The docs are actually only a selection tool to weed out feeble users. Try `ghcjs-boot --no-haddock --no-prof -s data/boot.tar` instead. It works for me.

If anything is wrong with your previous commands, try instead the invocation at the end of https://github.com/ghcjs/ghcjs/issues/740

If that fails, there's another sure medicine here: https://github.com/ghcjs/ghcjs/pull/726

What is your architecture/OS, BTW?

**Comment by luite** [comment]
This seems to happen if you use a new `cabal-install` version (newer than 2.4). The `ghcjs-boot` tool should be updated to use newer commands for that

**Comment by hansroland** [comment]
@luite Thanks for the hint with the cabal version. Going back from `cabal-install-2.4.0.1` to `cabal-install-2.4.0.0` solved the issue.
