### ISSUE TITLE
Not in scope: type variable 'a'

### ISSUE THREAD

**Issue by dmjio** [ghcjs/ghcjs#751]
Unsure if this has been resolved, `nixpkgs-unstable` and `nixos-unstable` are running into this issue when attempting to build `ghc-api-ghcjs` before `ghcjs`.

```haskell
dist/build/Parser.hs:1473:48: error:
    Not in scope: type variable ‘a’
     |
1473 | newtype HappyWrap209 = HappyWrap209 (([Located a],Bool))
     |   ```

**Comment by dmjio** [comment]
Using an older `happy` fixed this, cc @cocreature

**Comment by matthewbauer** [comment]
I just noticed this with ghcHEAD as well:

https://hydra.nixos.org/build/93826143

Is there some extension needed here?

**Comment by cdsmith** [comment]
@dmjio I'm running into this same problem.  Which version of happy worked for you?

**Comment by dmjio** [comment]
@cdsmith, ended up using `1.19.9` per @cocreature's advice. 

```nix
 happy = dontCheck (super.callHackage "happy" "1.19.9" {});
```

made things "happy" for me.

**Comment by matthewbauer** [comment]
Upstream bug: https://gitlab.haskell.org/ghc/ghc/issues/16652

**Comment by cdsmith** [comment]
Thanks!

**Comment by dmjio** [comment]
Think we're good here, please re-open if not.
