### ISSUE TITLE
ghcjs-boot failing while running hsc2hs-ghcjs

### ISSUE THREAD

**Issue by cdsmith** [ghcjs/ghcjs#755]
Now on fresh install of Debian 9, `ghcjs-boot` is failing.  This is the end of the output:

    Preprocessing library for base-4.12.0.0..
    cFailed to install base-4.12.0.0
    abal: The program 'hsc2hs' is required but the version of
    /home/cdsmith/codeworld/build/bin/hsc2hs-ghcjs could not be determined.

    cabal: Error: some packages failed to install:
    base-4.12.0.0-BGkpKxWDclNH5NZN2wRc8Q failed during the building phase. The
    exception was:
    ExitFailure 1
    transformers-0.5.6.2-KaPP0fdMTwBF02jPgfEE5s depends on transformers-0.5.6.2
    which failed to install.
    
    ghcjs-boot: error running: /home/cdsmith/codeworld/build/bin/cabal --config-file /home/cdsmith/.ghcjs/x86_64-linux-8.6.0.1-8.6.5/ghcjs/cabalBootConfig --ignore-sandbox install ./pkg/base ./pkg/integer-gmp ./pkg/transformers --allow-boot-library-installs --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /home/cdsmith/codeworld/build/bin/ghcjs --with-hc-pkg /home/cdsmith/codeworld/build/bin/ghcjs-pkg --prefix /home/cdsmith/.ghcjs/x86_64-linux-8.6.0.1-8.6.5/ghcjs --disable-documentation --haddock-html --haddock-hoogle --haddock-hyperlink-source --enable-debug-info --disable-library-stripping --disable-executable-stripping -fghci --disable-profiling --enable-shared
    exit status: 1
    stderr: Warning: The install command is a part of the legacy v1 style of cabal usage.

    Please switch to using either the new project style and the new-install
    command or the legacy v1-install alias as new-style projects will become the
    default in the next version of cabal-install. Please file a bug if you cannot
    replicate a working v1- use case with the new-style commands.
    
    For more information, see: https://wiki.haskell.org/Cabal/NewBuild
    
    Warning: cannot determine version of
    /home/cdsmith/codeworld/build/bin/hsc2hs-ghcjs :
    ""
    Warning: the --global flag is deprecated -- it is generally considered a bad
    idea to install packages into the global store
    Warning: No remote package servers have been specified. Usually you would have
    one specified in the config file.
    configure: WARNING: unrecognized options: --with-compiler, --with-hc-pkg
    configure: WARNING: unrecognized options: --with-compiler, --with-hc-pkg
    configure: WARNING: unrecognized options: --with-compiler, --with-hc-pkg
    configure: WARNING: unrecognized options: --with-compiler, --with-hc-pkg
    cabal: The program 'hsc2hs' is required but the version of
    /home/cdsmith/codeworld/build/bin/hsc2hs-ghcjs could not be determined.
    
    cabal: Error: some packages failed to install:
    base-4.12.0.0-BGkpKxWDclNH5NZN2wRc8Q failed during the building phase. The
    exception was:
    ExitFailure 1
    transformers-0.5.6.2-KaPP0fdMTwBF02jPgfEE5s depends on transformers-0.5.6.2
    which failed to install.

I did trace down the program, and the symlink is fine, but the program itself is failing:

    $ hsc2hs-ghcjs --version
    hsc2hs-ghcjs: hsc2hs: rawSystem: runInteractiveProcess: exec: does not exist (No such file or directory)

**Comment by cdsmith** [comment]
This did seem to work on an earlier attempt.  The only difference was that the other time, I installed and bootstrapped cabal by hand after installing GHC from the binary distribution.  But this time, I used `ghcup` to install both GHC and cabal.  I'm not sure why that should make a difference.

**Comment by jneira** [comment]
mmm, maybe it needs `hsc2hs` in $PATH, it is included with a normal ghc installation but maybe `ghcup` didn't add the $GHC_ROOT/bin to PATH?

**Comment by sjakobi** [comment]
> mmm, maybe it needs `hsc2hs` in $PATH

Right. When I installed `hsc2hs` via `cabal` the issue didn't reappear.

> maybe `ghcup` didn't add the $GHC_ROOT/bin to PATH

Indeed. Comparing `.ghcup/bin` with `.ghcup/ghc/8.6.5/bin`, `hsc2hs`, `hp2ps` and `hpc` are missing.

**Comment by sjakobi** [comment]
I've made a report at https://gitlab.haskell.org/haskell/ghcup/issues/104.

**Comment by cdsmith** [comment]
So nothing to do here (except maybe add a note in the README).

**Comment by hasufell** [comment]
Please test https://gitlab.haskell.org/haskell/ghcup/merge_requests/103
