### ISSUE TITLE
Reduce Memory Usage when linking Executable with complex Libraries

### ISSUE THREAD

**Issue by marcpabst** [ghcjs/ghcjs#758]
I tried to compile Pandoc with ghcjs for a few days now and after removing some dependencies and disabling TH I got ghcjs to compile Pandoc and all its dependencies just fine. I then adapted one of the examples from the Pandoc manual:

    import Text.Pandoc
    import qualified Data.Text as T
    import qualified Data.Text.IO as TIO
    
    main :: IO ()
    main = do
    result <- runIO $ do
        doc <- readMarkdown def (T.pack "[testing](url)")
        writeHtml5String def doc
    m <- handleError result
    TIO.putStrLn m

It work fine using standard GHC. Using GHCJS however, the linker seems to go crazy and aborts after some time:

    Build profile: -w ghcjs-8.4.0.1 -O1
    In order, the following will be built (use -v for more details):
     - test-0.1.0.0 (exe:test) (file Main.hs changed)
    Preprocessing executable 'test' for test-0.1.0.0..
    Building executable 'test' for test-0.1.0.0..
    Linking [...]/test/dist-newstyle/build/x86_64-linux/ghcjs-8.4.0.1/test-0.1.0.0/x/test/build/test/test.jsexe (Main)
    ghcjs: internal error: Unable to commit 1048576 bytes of memory
        (GHC version 8.4.4 for x86_64_unknown_linux)
        Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
    cabal: Failed to build exe:test from test-0.1.0.0. The build process was
    killed (i.e. SIGKILL). The typical reason for this is that there is not enough
    memory available (e.g. the OS killed a process using lots of memory).

I already upped the memory to 32G of RAM and 32G of swap and it still seems not enough. Is there any way to reduce the memory usage of the linker?

**Comment by sigrlami** [comment]
@marcpabst do you have example repo for test? How ghcjs was compiled?

**Comment by ddssff** [comment]
Pandoc may be the most challenging package for ghcjs that I've come across.  We now build the pandoc-types package for ghcjs but not pandoc.  For converting markdown to html you could use cheapskate and blaze-html.

**Comment by sigrlami** [comment]
@ddssff this webapp https://github.com/osener/markup.rocks uses Pandoc successfully and I have successfull builds with 8.0/8.2 versions. It can provide very powerful set of functions.

**Comment by marcpabst** [comment]
> @ddssff this webapp https://github.com/osener/markup.rocks uses Pandoc successfully and I have successfull builds with 8.0/8.2 versions. It can provide very powerful set of functions.

This actually is where I drew inspiration from. The repo for my test application can be found here [https://github.com/marcpabst/pandoc-test](https://github.com/marcpabst/pandoc-test). Check the `cabal.project` for GHCSJ and my [custom pandoc repo](https://github.com/marcpabst/pandoc).

For GHCJS, I followed [these instruction](https://www.reddit.com/r/haskell/comments/ajk9th/you_dont_need_reflexplatform_to_use_ghcjs_or/eewrzp9?utm_source=share&utm_medium=web2x) which worked fine so far, granted I've only used it on a small test project.

@ddssff thanks but I really want to leverage pandoc because it is in many ways superior to all other available options I know of.

**Comment by sigrlami** [comment]
@marcpabst I'll take a look and let you know if I can reproduce it.

**Comment by marcpabst** [comment]
> @marcpabst I'll take a look and let you know if I can reproduce it.

Thanks. I'm quite new to GHC/GHCJS/Haskell and it might be very well the case that I made some stupid mistake. But since there is no error it's quite hard for me to investigate. 

I'm a little inclined to set up a large swap file (1TB) and let it sit overnight to see if is a real problem or just  bad memory management. But since others (including you) were able to build Pandoc without these comically large amounts of memory, I'm sure there is something to do about.

**Comment by marcpabst** [comment]
Thanks to @sigrlami I was able to build GHCJS from scratch but I still face the same problem. I now suspect that there might be one or two Pandoc dependency that simply face too much of an challenge for GHCJS. 
**Is there any way to get more information on the linking process** to identify problematic packages? I tried the `-v3` flag but it didn't help.

**Comment by ddssff** [comment]
Did this work out?

**Comment by marcpabst** [comment]
At the time regrettably not. However, I kinda lost interest so I can't tell if this issue was solved or not. If I find the time I will try again and reopen this issue if necessary.
