### ISSUE TITLE
uncaught exception in Haskell thread: ReferenceError: h$baseZCGHCziBaseziJust_con_e is not defined

### ISSUE THREAD

**Issue by tomsmalley** [ghcjs/ghcjs#760]
Just bumped to the 8.6 branch of reflex-platform, and I'm hitting what appears to be a GHCJS bug:

```
uncaught exception in Haskell thread: ReferenceError: h$baseZCGHCziBaseziJust_con_e is not defined
```

@luite any thoughts on this?

**Comment by luite** [comment]
Should be fixed by the pull request from Ali. Please reopen if you still see this.
