### ISSUE TITLE
Internal library support

### ISSUE THREAD

**Issue by cdfa** [ghcjs/ghcjs#806]
Hi! I'm trying to use an internal library in my project, but it seems ghcjs can never find the modules it exposes when I try to import them in my executable component. Normal ghc does work. It seems weird to me that this is a ghcjs issue, but I've done everything I know how to do to pin down the issue.

Specifically, I'm using ghcjs with Nix and Miso to build a web app. Switching out ghcjs for ghc 8.6.5 in my root nix expression fixes the issue. Of course, this triggers changes outside of ghcjs as well, so to be sure the issue is with ghcjs I would need to do a pure ghcjs + cabal reproduction repo. I'm sure I can figure out how to do this at some point, but until I find time to do so, any pointers to a minimal reproduction repo I can fork would be greatly appreciated.

As a final note: it seems I'm not the only one experiencing this issue: https://github.com/alasconnect/data-validation/pull/7/files#r428861077

**Comment by Mikolaj** [comment]
Did you try with older GHCs? I don't remember when, but at some point GHC stopped exporting private internal libraries from packages. Perhaps GHCJS did it a bit earlier? Does it sound like your problem?

**Comment by Mikolaj** [comment]
I'm sorry, I mean *newer* GHCs.

**Comment by cdfa** [comment]
Have they? If they are not supported anymore it might be better to not rely on them anyway. [This issue](https://github.com/commercialhaskell/stack/issues/4564#issue-406782814) seems relatively alive though. Do you have a pointer to an announcement or anything like that?

**Comment by Mikolaj** [comment]
No, I don't have a pointer. You got me wrong: *private* internal libraries are not *exported*, not "all internal libraries are not supported". If you want to export an internal library you need to make it public. Alternatively, re-export all modules you need in the main library of the package.

**Comment by cdfa** [comment]
Ahh, I misread that. My apologies. I don't think that's the issue though, because I'm trying to use the internal library internally (in the executable component of the same package). That should be working right?

**Comment by Mikolaj** [comment]
Yes, this should work fine.

**Comment by cdfa** [comment]
Seems to be working right on 8.10🎉
