### ISSUE TITLE
Not in scope: data constructor `ArchAArch64'

### ISSUE THREAD

**Issue by falsifian** [ghcjs/ghcjs#810]
Building at head (commit e4cd4232a31f6371c761acd93853702f4c7ca74c) I see:
```
[ 87 of 577] Compiling Reg              ( ghc/compiler/nativeGen/Reg.hs, dist/build/Reg.o, dist/build/Reg.dyn_o )
[ 88 of 577] Compiling RegAlloc.Graph.TrivColorable ( ghc/compiler/nativeGen/RegAlloc/Graph/TrivColorable.hs, dist/build/RegAlloc/Graph/TrivColorable.o, dist/build/RegAlloc/Graph/TrivColorable.dyn_o )

ghc/compiler/nativeGen/RegAlloc/Graph/TrivColorable.hs:118:29: error:
    Not in scope: data constructor `ArchAArch64'
    |
118 |                             ArchAArch64   -> panic "trivColorable ArchAArch64"
    |                             ^^^^^^^^^^^

ghc/compiler/nativeGen/RegAlloc/Graph/TrivColorable.hs:149:29: error:
    Not in scope: data constructor `ArchAArch64'
    |
149 |                             ArchAArch64   -> panic "trivColorable ArchAArch64"
    |                             ^^^^^^^^^^^

ghc/compiler/nativeGen/RegAlloc/Graph/TrivColorable.hs:182:29: error:
    Not in scope: data constructor `ArchAArch64'
    |
182 |                             ArchAArch64   -> panic "trivColorable ArchAArch64"
    |                             ^^^^^^^^^^^
cabal: Failed to build ghcjs-8.10.5 (which is required by exe:haddock from
ghcjs-8.10.5, exe:ghcjs-pkg from ghcjs-8.10.5 and others). See the build log
above for details.
```

This in on NixOS, with environment created using `nix-shell --pure -p autoconf git haskellPackages.cabal-install haskellPackages.ghc haskellPackages.alex python39`, and simply running `cabal v2-install`. 

I was able to work around the problem locally by replacing `ArchAArch64` with `ArchARM64` in the ghcjs source. The problem has something to do with mismatched `ghc-boot` versions. Maybe a version constraint should be added to `ghcjs.cabal`?

I also wonder if I'm missing steps. The README says "GHCJS depends on a few "local" packages in the source tree. You can use cabal-install and stack to set up a build environment that contains these packages." but I don't know how to interpret that --- what exactly am I supposed to put in my build environment?

See also https://github.com/NixOS/nixpkgs/issues/133271 for my attempts to package it as part of nixpkgs, which ran into a similar problem.

**Comment by dfordivam** [comment]
@falsifian the ghcjs needs the same major release of ghc as itself, so in this case 8.10.5. 
The 8.10.6 has just been release and merged in nixpkgs, so it might be able to build the ghcjs 8.10.5 as well as it has ArchAArch64.
(I saw your efforts of adding ghcjs in nixpkgs, and I have been making the same efforts myself recently and have progressed some more)

**Comment by falsifian** [comment]
Thanks for the info @dfordivam. Feel free to close if matching versions is likely to resolve this issue (I'm no longer working on it). (Maybe consider updating the README to mention the versions should match.)

**Comment by dfordivam** [comment]
Ok, it is mentioned in the README. (edit: I dont have the rights to close the issue, you may do that instead)

`You need the same major version of GHC as the version of the GHCJS branch you're building.`

**Comment by dfordivam** [comment]
There is even a check which fails the compilation, even if there are no compile errors. This means that I will have to port the ghcjs to 8.10.6 (same as nixpkgs)

```
Configuring ghc-prim-0.6.1...
Setup: Version mismatch between ghcjs and ghcjs-pkg:
/nix/store/m9agdh0nkfy1dvnxygq7bvfm3x8xg09j-ghcjs-8.10.5/bin/ghcjs was built
with GHC version 8.10.6
/nix/store/m9agdh0nkfy1dvnxygq7bvfm3x8xg09j-ghcjs-8.10.5/bin/ghcjs-pkg was
built with GHC version 8.10.5
```

**Comment by falsifian** [comment]
Oops, I either missed that line in the README or didn't understand "major" version included all three numbers.

I did see the `was built with...` failure, but did not realize this was the cause. (I still don't understand how `ghcjs` ends up being built with `8.10.6` if my installed GHC is `8.10.5`... the only `8.10.6` I have around is `ghcjs` itself, and surely `ghcjs` can't build itself, because it only targets Javascript?)

In any case, closing this issue.
